window.POJU_SKILLS = [
  {
    "n": 1,
    "id": "poju-001",
    "name": "个人工作台生成器",
    "cat": "工具",
    "brief": "个人工作台生成器：将个人专属工作台封装为可复用的单文件网页。支持“生成器模式”根据领域关键词定制，或“模板库模式”交付干净模板供用户自行修改。内置毛玻璃拟态风格、7大功能页面及本地存储逻辑，严格遵循安全规范，不内含任何真实凭证或私有链接。",
    "author": "小程",
    "folder": "个人工作台生成器",
    "zip": "resources/skill-kit/packs/001-个人工作台生成器.zip",
    "page": "resources/skill-kit/index.html#poju-001"
  },
  {
    "n": 2,
    "id": "poju-002",
    "name": "心理咨询/观察者咨询系统",
    "cat": "学习教育",
    "brief": "POS 观察者咨询系统是一款 AI 引导的心理自助工具。它基于“POS 并行操作系统”的观察者层理念，为用户提供结构化的自我观察流程。当用户面临情绪困扰、困境或两难问题时，AI 将扮演“养育者”角色，先接住情绪并引导用户稳定状态，随后通过“往下看”（探索痛苦根源）和“往前看”（明确现实需求）的双轨路径，帮助用户区分事实…",
    "author": "小程",
    "folder": "心理咨询_观察者咨询系统",
    "zip": "resources/skill-kit/packs/002-心理咨询_观察者咨询系统.zip",
    "page": "resources/skill-kit/index.html#poju-002"
  },
  {
    "n": 3,
    "id": "poju-003",
    "name": "投资思维十三法则",
    "cat": "数据分析",
    "brief": "投资思维十三法则：一套基于王川方法论蒸馏的投资决策系统。包含十三条互为配套的思维法则（如能力圈判定、简单为王、趋势为王等），覆盖从入场评估到长期持有的完整决策链。内置可运行的持仓体检器（Python 脚本），支持输入持仓数据后逐条打分，一键生成结构化测试分析报告与交互式风险热力图看板，帮助用户识别最薄弱点、推演失败路径…",
    "author": "Alan-杨海",
    "folder": "投资思维十三法则",
    "zip": "resources/skill-kit/packs/003-投资思维十三法则.zip",
    "page": "resources/skill-kit/index.html#poju-003"
  },
  {
    "n": 4,
    "id": "poju-004",
    "name": "营销内容创作",
    "cat": "写作",
    "brief": "本 Skill 提供营销内容创作与分发服务，支持三种互斥链路：纯文案创作（不发布）、公众号图文创作并发布至草稿箱、小红书/朋友圈图文创作并保存入库。通过智能路由判断用户需求，自动执行商品查询、图片生成、文案撰写及接口调用，确保内容合规且高效产出。",
    "author": "Alan-杨海",
    "folder": "营销内容创作",
    "zip": "resources/skill-kit/packs/004-营销内容创作.zip",
    "page": "resources/skill-kit/index.html#poju-004"
  },
  {
    "n": 5,
    "id": "poju-005",
    "name": "群聊日报生成器",
    "cat": "工具",
    "brief": "将导出的聊天记录（HTML/TXT/PDF）按天蒸馏为格式一致的 HTML 日报。包含总体看板（主题数、发言数、同比等）、分类归档及关键提示。全程本地处理，自动过滤寒暄与敏感话题，支持手机号/身份证脱敏，确保数据安全与跨天可比性。",
    "author": "Alan-杨海",
    "folder": "群聊日报生成器",
    "zip": "resources/skill-kit/packs/005-群聊日报生成器.zip",
    "page": "resources/skill-kit/index.html#poju-005"
  },
  {
    "n": 6,
    "id": "poju-006",
    "name": "群聊导出 HTML 提纯",
    "cat": "工具",
    "brief": "本 Skill 专用于解析微信或飞书群聊导出的大型 HTML 文件（通常 10MB+），将其蒸馏为结构化的信息简报。流程包括：HTML 转纯文本、去噪处理、分段并行提取关键信息、交叉合并及可信度分级。最终生成包含话题地图、关键信息台账、未决事项清单和风险提示的 Markdown 报告，并提供 HTML 预览功能。适用于…",
    "author": "Alan-杨海",
    "folder": "群聊导出 HTML 提纯",
    "zip": "resources/skill-kit/packs/006-群聊导出-HTML-提纯.zip",
    "page": "resources/skill-kit/index.html#poju-006"
  },
  {
    "n": 7,
    "id": "poju-007",
    "name": "Windows 无管理员常驻守护",
    "cat": "开发运维",
    "brief": "Windows 用户态常驻守护工具，专为无管理员权限环境设计。通过在 Startup 目录放置 VBS 启动器，由 explorer.exe 拉起 Python 看门狗脚本，实现后台进程的登录自启与崩溃自动重启。支持 HTTP 端口探测和进程名监控两种健康检查模式，具备单实例保护、僵尸进程清理及日志轮转功能。适用于 A…",
    "author": "Alan-杨海",
    "folder": "Windows 无管理员常驻守护",
    "zip": "resources/skill-kit/packs/007-Windows-无管理员常驻守护.zip",
    "page": "resources/skill-kit/index.html#poju-007"
  },
  {
    "n": 8,
    "id": "poju-008",
    "name": "旧版 MongoDB 桥接",
    "cat": "开发运维",
    "brief": "专为 MongoDB 3.x 等老旧版本设计的桥接方案，解决新版官方工具（如 MongoDB Compass 1.40+ 和 mongodb-mcp-server）无法连接低版本数据库的问题。Skill 提供了基于 pymongo 3.13.0 的纯 Python MCP 服务器实现，支持 list-databases…",
    "author": "Alan-杨海",
    "folder": "旧版 MongoDB 桥接",
    "zip": "resources/skill-kit/packs/008-旧版-MongoDB-桥接.zip",
    "page": "resources/skill-kit/index.html#poju-008"
  },
  {
    "n": 9,
    "id": "poju-009",
    "name": "MCP 冒烟测试",
    "cat": "开发运维",
    "brief": "MCP stdio 冒烟测试：当 MCP 服务器已配置但未在 UI 中 Trust 时，使用此 Skill 直接拉起子进程进行端到端验证。支持 initialize 握手、tools/list 列表获取及 tools/call 实际调用，帮助快速定位连接问题或验证服务器可用性，无需重载会话。",
    "author": "Alan-杨海",
    "folder": "MCP 冒烟测试",
    "zip": "resources/skill-kit/packs/009-MCP-冒烟测试.zip",
    "page": "resources/skill-kit/index.html#poju-009"
  },
  {
    "n": 10,
    "id": "poju-010",
    "name": "视频下载归档",
    "cat": "音视频",
    "brief": "一款专用的视频下载与归档 Skill，支持抖音、小红书、B站、YouTube 和微信视频号等平台。用户只需提供分享链接或本地路径，即可自动下载为 MP4 文件。内置 ffprobe 校验机制，确保视频流、音频流、时长及分辨率有效。特别针对微信视频号提供了多种解析方案（包括元宝登录态、公共 Worker 及 Cookie…",
    "author": "Alan-杨海",
    "folder": "视频下载归档",
    "zip": "resources/skill-kit/packs/010-视频下载归档.zip",
    "page": "resources/skill-kit/index.html#poju-010"
  },
  {
    "n": 11,
    "id": "poju-011",
    "name": "仓颉技能工坊",
    "cat": "研究检索",
    "brief": "仓颉技能工坊：一个基于 RIA-TV++ 流水线的元 Skill，旨在将书籍、长视频、播客等长内容蒸馏为一组原子化、可被 Agent 直接调用的可执行 Skills。通过定向提取、三重校验、压力测试等阶段，从非结构化文本中提取框架、原则和方法论，生成标准化的 Skill 包并安装到宿主环境。适用于拆书、知识蒸馏及构建可…",
    "author": "Alan-杨海",
    "folder": "仓颉技能工坊",
    "zip": "resources/skill-kit/packs/011-仓颉技能工坊.zip",
    "page": "resources/skill-kit/index.html#poju-011"
  },
  {
    "n": 12,
    "id": "poju-012",
    "name": "书单号视频",
    "cat": "音视频",
    "brief": "输入书名和作者，自动生成 1080P 竖屏书单短视频。支持 AI 配图、AI 配音、中英双语字幕及 Ken Burns 运镜效果。内置《人性的弱点》等畅销书模板，开箱即用。适用于短视频内容创作与自动化生产。",
    "author": "AI 设计老赵",
    "folder": "书单号视频",
    "zip": "resources/skill-kit/packs/012-书单号视频.zip",
    "page": "resources/skill-kit/index.html#poju-012"
  },
  {
    "n": 13,
    "id": "poju-013",
    "name": "公众号写作流水线",
    "cat": "写作",
    "brief": "公众号写作助手。从选题到排版一站式对话流。支持热点追踪、灵感创作、文章改写及风格学习四种路径。内置四层质检与敏感词检测，自动生成 HTML 排版代码及配图方案，帮助用户高效完成公众号文章创作。",
    "author": "AI 设计老赵",
    "folder": "公众号写作流水线",
    "zip": "resources/skill-kit/packs/013-公众号写作流水线.zip",
    "page": "resources/skill-kit/index.html#poju-013"
  },
  {
    "n": 14,
    "id": "poju-014",
    "name": "站在用户立场思考",
    "cat": "研究检索",
    "brief": "这是一套将「站在用户角度思考」转化为可执行动作的商业判断工具。基于 7-Eleven 创始人铃木敏文的理念，通过「5 把铲子」认知转换工具和「9 个视角」洞察工具，帮助用户从卖方立场切换到用户代理人视角。适用于产品经理、品牌营销及创业者，用于判断产品可行性、挖掘创新机会、评审商业方案，从而摆脱同质化竞争，输出明确的用户…",
    "author": "潘达",
    "folder": "站在用户立场思考",
    "zip": "resources/skill-kit/packs/014-站在用户立场思考.zip",
    "page": "resources/skill-kit/index.html#poju-014"
  },
  {
    "n": 15,
    "id": "poju-015",
    "name": "优质选题操盘手",
    "cat": "写作",
    "brief": "这是一个针对内容创作者的选题深化与大纲构建工具。它能围绕用户提供的初始论点，通过多轮结构化对话逐层挖掘认知深度。技能内置了“现象、误区、根因、新解、做法、格局”六大分析板块，并采用“旧认知—新增点—解释价值—行动影响”的四问验收标准，确保每一轮讨论都产生实质性的认知增量。在对话结束后，助手会自动进行主线相关性审计，剔除…",
    "author": "彩霞",
    "folder": "优质选题操盘手",
    "zip": "resources/skill-kit/packs/015-优质选题操盘手.zip",
    "page": "resources/skill-kit/index.html#poju-015"
  },
  {
    "n": 16,
    "id": "poju-016",
    "name": "专业型IP公众号创作专家",
    "cat": "写作",
    "brief": "由资深商业增长顾问与AI创新应用专家打磨的公众号内容创作教练。整合爆款标题24公式、去AI味8技法、对抗式多智能体审核与商业计划书三要素定位，帮创作者产出犀利、极简、经得起读者质疑的高质感公众号文章。触发场景：写公众号文章、优化结构、提炼金句、商业案例拆解、爆款标题策划、素材二创、内容风格诊断。适用人群：希望用结构化方…",
    "author": "洪帮主AI创新增长",
    "folder": "专业型IP公众号创作专家",
    "zip": "resources/skill-kit/packs/016-专业型IP公众号创作专家.zip",
    "page": "resources/skill-kit/index.html#poju-016"
  },
  {
    "n": 17,
    "id": "poju-017",
    "name": "人生重大决策专家",
    "cat": "学习教育",
    "brief": "由商业增长顾问洪帮主打造的「个人与创业决策诊断系统」。自动识别用户类型（个人生活 vs 创业者），分别调用元能力飞轮诊断或12步决策流水线。利用纳瓦尔三问、四维元能力矩阵、复利匹配与现金流测算，将模糊困扰转化为可执行的决策方案。适用于职业抉择、副业选择、创业方向、投资决策等重大场景，提供深度报告与行动闭环指导。",
    "author": "洪帮主AI创新增长",
    "folder": "人生重大决策专家",
    "zip": "resources/skill-kit/packs/017-人生重大决策专家.zip",
    "page": "resources/skill-kit/index.html#poju-017"
  },
  {
    "n": 18,
    "id": "poju-018",
    "name": "专业知识库自动构建&归档引擎",
    "cat": "工具",
    "brief": "这是一个知识库文件自动归档引擎，基于PARA + IPO双框架设计。它能自动判断文件归属目录、生成合规文件名（清理非法字符）、并正确放置文件。支持公众号文章、课程大纲、客户记录等多种类型文件的智能分类与归档，帮助用户建立系统化、结构化的个人知识库，提升知识管理效率。",
    "author": "洪帮主AI创新增长",
    "folder": "专业知识库自动构建&归档引擎",
    "zip": "resources/skill-kit/packs/018-专业知识库自动构建-归档引擎.zip",
    "page": "resources/skill-kit/index.html#poju-018"
  },
  {
    "n": 19,
    "id": "poju-019",
    "name": "CEO精力管理诊断专家",
    "cat": "工具",
    "brief": "由商业增长顾问洪帮主打造的「CEO精力健康度诊断专家」，专为初创企业创始人设计的精力治理工具。核心理念是“每个人都是自己的人生CEO”，旨在帮助用户从“时间管理”升级为“精力管理”。整合「精力5维评估法」、「三大精力黑洞」（优势沉溺、机会劫持、琐事吞噬）及「阻塞项/杠杆项/未来项」分类框架。通过5步诊断流程（黑洞定位→…",
    "author": "洪帮主AI创新增长",
    "folder": "CEO精力管理诊断专家",
    "zip": "resources/skill-kit/packs/019-CEO精力管理诊断专家.zip",
    "page": "resources/skill-kit/index.html#poju-019"
  },
  {
    "n": 20,
    "id": "poju-020",
    "name": "商业创新项目画布推演专家",
    "cat": "写作",
    "brief": "本Skill是基于Osterwalder商业模式画布（BMC）九要素打造的AI推演引擎。它遵循“前台价值创造→后台交付支撑→商业闭环验证”的主线，引导用户从客户洞察到商业落地完成系统化推演。配套12步完整链路及双维画像、JTBD场景穷举、上瘾模型等专家方法论，支持全流程推演、单点深挖和一致性诊断三种模式，适用于商业模式…",
    "author": "洪帮主AI创新增长",
    "folder": "商业创新项目画布推演专家",
    "zip": "resources/skill-kit/packs/020-商业创新项目画布推演专家.zip",
    "page": "resources/skill-kit/index.html#poju-020"
  },
  {
    "n": 21,
    "id": "poju-021",
    "name": "副业&职业加速成长教练",
    "cat": "学习教育",
    "brief": "这是一个由商业增长顾问洪帮主打造的IPO成长飞轮教练Skill。它利用原创的IPO（输入→加工→输出）循环飞轮模型和以终为始框架，帮助用户诊断在个人能力成长、副业增收及商业闭环布局中的具体卡点。Skill支持个人成长、副业变现、企业增长及AI工具焦虑等多种场景，通过标准化的健康度自测、系统性闭环蓝图生成及30天行动卡，…",
    "author": "洪帮主AI创新增长",
    "folder": "副业&职业加速成长教练",
    "zip": "resources/skill-kit/packs/021-副业-职业加速成长教练.zip",
    "page": "resources/skill-kit/index.html#poju-021"
  },
  {
    "n": 22,
    "id": "poju-022",
    "name": "创新创业项目评估专家",
    "cat": "研究检索",
    "brief": "创新项目评审专家·通用版。以「商业增长顾问 + AI创新应用顾问」双视角，基于 RWW（Real-Win-Worth）三问六子问模型，对课题/项目进行内部创投式评审。适用于互联网、消费、制造、医疗、SaaS、教育等任意行业的一般创新项目。支持解析录音、PPT、PDF 等多种材料，输出包含 RWW 逐项评估、优劣势矩阵、…",
    "author": "洪帮主AI创新增长",
    "folder": "创新创业项目评估专家",
    "zip": "resources/skill-kit/packs/022-创新创业项目评估专家.zip",
    "page": "resources/skill-kit/index.html#poju-022"
  },
  {
    "n": 23,
    "id": "poju-023",
    "name": "中文出版书稿撰写&格式规范检查与修复技能（机械工业版本）",
    "cat": "工具",
    "brief": "中文出版书稿格式规范检查与修复技能。当用户需要对中文书稿（.docx）进行出版格式审查、消除AI写作痕迹、修正编号格式、或按出版社反馈修改稿件时使用此技能。典型触发场景：出版社退修稿件、书稿格式规范化、AI味检测与消除、编号格式统一。",
    "author": "石头AI",
    "folder": "中文出版书稿撰写&格式规范检查与修复技能（机械工业版本）",
    "zip": "resources/skill-kit/packs/023-中文出版书稿撰写-格式规范检查与修复技能-机械工业版本.zip",
    "page": "resources/skill-kit/index.html#poju-023"
  },
  {
    "n": 24,
    "id": "poju-024",
    "name": "书稿示意图生成技能",
    "cat": "设计",
    "brief": "书稿示意图生成技能。当用户需要为技术书、商业书等书稿生成章节示意图时使用此技能。支持流程图、架构图、对比图、状态图、关系图等多种类型。输出格式为单页HTML文件（内含SVG），可在浏览器预览后截图嵌入Word。触发场景：生成书稿示意图、出流程图、画架构图、章节配图、书稿插图制作。",
    "author": "石头AI",
    "folder": "书稿示意图生成技能",
    "zip": "resources/skill-kit/packs/024-书稿示意图生成技能.zip",
    "page": "resources/skill-kit/index.html#poju-024"
  },
  {
    "n": 25,
    "id": "poju-025",
    "name": "企业战略洞察报告专家技能",
    "cat": "写作",
    "brief": "这是一个可配置的“战略洞察报告专家”数字员工技能。它通过「角色 × 行业 × 框架」三参数配置，结合 BLM 五看、波特五力等咨询框架，生成结构完整、数据有出处且去 AI 味的专家级报告。核心亮点包括：1. 闭环工作流：涵盖摸底、澄清、研究、写作、验证五阶段，确保逻辑严密；2. 循环进化引擎：通过 L1/L2 分层沉淀…",
    "author": "石头AI",
    "folder": "企业战略洞察报告专家技能",
    "zip": "resources/skill-kit/packs/025-企业战略洞察报告专家技能.zip",
    "page": "resources/skill-kit/index.html#poju-025"
  },
  {
    "n": 26,
    "id": "poju-026",
    "name": "FDE企业交付避坑自检技能",
    "cat": "工具",
    "brief": "这是一款专为企业AI交付场景设计的避坑自检助手。在接单、POC演示、签约或上线前，用户可通过输入客户类型、单子阶段及金额量级等信息，触发对10个已知风险点（包括AI时代特有坑与经典ToB坑）的逐项扫描。系统将根据规避情况判定整体风险等级（高/中/低），并生成包含必处理项与建议项的自检报告，帮助用户识别潜在陷阱，辅助决策…",
    "author": "石头AI",
    "folder": "FDE企业交付避坑自检技能",
    "zip": "resources/skill-kit/packs/026-FDE企业交付避坑自检技能.zip",
    "page": "resources/skill-kit/index.html#poju-026"
  },
  {
    "n": 27,
    "id": "poju-027",
    "name": "AI 图片生成器（通义万相）",
    "cat": "设计",
    "brief": "使用魔搭 ModelScope 的通义万相模型生成高质量 AI 图片：自然语言描述即可出图，自动将中文描述优化为英文提示词，支持 Z-Image-Turbo 快速生成与 Z-Image 高质量两种模型，配置 ModelScope API Key 环境变量即可使用。",
    "author": "雪见RPA+AI",
    "folder": "AI 图片生成器（通义万相）",
    "zip": "resources/skill-kit/packs/027-AI-图片生成器-通义万相.zip",
    "page": "resources/skill-kit/index.html#poju-027"
  },
  {
    "n": 28,
    "id": "poju-028",
    "name": "电商详情页文案工厂",
    "cat": "写作",
    "brief": "电商详情页文案工厂，专为淘宝、拼多多、抖音等货架电商平台设计。该技能遵循真实的用户购买决策路径，按顺序生成高转化率的页面文案。主要功能包括：1. 主图文案生成：规划5张主图的结构化文案，涵盖卖点、痛点、信任背书及促销信息；2. 详情页模块文案：按照痛点共鸣、产品介绍、卖点展开（FAB法则）、竞品对比、信任背书、使用场景…",
    "author": "雪见RPA+AI",
    "folder": "电商详情页文案工厂",
    "zip": "resources/skill-kit/packs/028-电商详情页文案工厂.zip",
    "page": "resources/skill-kit/index.html#poju-028"
  },
  {
    "n": 29,
    "id": "poju-029",
    "name": "朋友圈营销文案",
    "cat": "写作",
    "brief": "一款专注于微信朋友圈营销的文案生成助手。它基于\"专业价值/客户见证/生活人设/产品促销\"四类黄金配比，帮助用户规划一周的朋友圈发布节奏。技能包含详细的单条文案结构模板（钩子、主体、落点、引导）、排版规则（短句断行、克制Emoji）以及反感度自检清单。旨在通过故事化表达和真实细节，降低硬广比例，避免刷屏感，帮助私域运营者…",
    "author": "雪见RPA+AI",
    "folder": "朋友圈营销文案",
    "zip": "resources/skill-kit/packs/029-朋友圈营销文案.zip",
    "page": "resources/skill-kit/index.html#poju-029"
  },
  {
    "n": 30,
    "id": "poju-030",
    "name": "直播间话术工厂",
    "cat": "写作",
    "brief": "直播间话术工厂，按真实直播节奏生成完整脚本或单环节逐字稿。涵盖开场暖场、留人憋单、FABG产品讲解、互动提问、逼单促销、过款转场及下播预告七大环节。内置服装、美食、美妆、知识付费、百货五类品类模板，提供防冷场过渡句及广告法极限词合规替换表，确保话术口语化且符合平台规范。",
    "author": "雪见RPA+AI",
    "folder": "直播间话术工厂",
    "zip": "resources/skill-kit/packs/030-直播间话术工厂.zip",
    "page": "resources/skill-kit/index.html#poju-030"
  },
  {
    "n": 31,
    "id": "poju-031",
    "name": "小红书搜索关键词布局",
    "cat": "写作",
    "brief": "小红书搜索关键词布局工具。根据产品或主题生成五类关键词矩阵（核心词/属性词/长尾词/竞品词/情绪词），提供标题埋点公式、正文与标签的布局方案以及发布前自检清单。帮助创作者通过科学的关键词工程，让笔记持续被搜索到，有效获取长尾流量。适用于需要提升小红书笔记搜索排名和自然曝光的场景。",
    "author": "雪见RPA+AI",
    "folder": "小红书搜索关键词布局",
    "zip": "resources/skill-kit/packs/031-小红书搜索关键词布局.zip",
    "page": "resources/skill-kit/index.html#poju-031"
  },
  {
    "n": 32,
    "id": "poju-032",
    "name": "小红书评论区运营助手",
    "cat": "写作",
    "brief": "小红书评论区运营助手，将评论区视为提升互动率和搜索流量的关键阵地。该技能可协助用户生成高赞置顶评论、暖场神评论及分类回复速查话术，提供评论区关键词埋点策略和杠精差评应对方案，并附带发布后30分钟黄金期运营动作清单，帮助笔记有效承接流量，提升互动数据。",
    "author": "雪见RPA+AI",
    "folder": "小红书评论区运营助手",
    "zip": "resources/skill-kit/packs/032-小红书评论区运营助手.zip",
    "page": "resources/skill-kit/index.html#poju-032"
  },
  {
    "n": 33,
    "id": "poju-033",
    "name": "data-analysis-ops",
    "cat": "数据分析",
    "brief": "数据分析与运营教练。基于《运营之路》框架，提供从数据预处理到科学运营建议的全流程指导。覆盖电商、内容、社交等多平台场景，内置描述性统计、RFM分层、趋势预测等分析方法，并输出可执行的 Excel/Python 代码及结构化运营方案，帮助用户将数据转化为业务洞察。",
    "author": "宛月",
    "folder": "data-analysis-ops",
    "zip": "resources/skill-kit/packs/033-data-analysis-ops.zip",
    "page": "resources/skill-kit/index.html#poju-033"
  },
  {
    "n": 34,
    "id": "poju-034",
    "name": "ai-product-framework",
    "cat": "设计",
    "brief": "AI 产品框架设计器。帮助产品经理从 0 到 1 设计并可视化 AI 产品的结构化框架，覆盖四大视图：分层架构（Layered Architecture）、价值链（Value Chain）、能力图谱（Capability Map）、竞争定位（Competitive Positioning）。支持产出可分享的框架图与自包…",
    "author": "宛月",
    "folder": "ai-product-framework",
    "zip": "resources/skill-kit/packs/034-ai-product-framework.zip",
    "page": "resources/skill-kit/index.html#poju-034"
  },
  {
    "n": 35,
    "id": "poju-035",
    "name": "weekly-meal-planner",
    "cat": "工具",
    "brief": "一款专业的科学一周饮食规划工具。从注册营养师视角出发，依据《中国居民膳食指南（2022）》和 DRIs 标准，为用户定制包含能量计算、食材轮换、详细菜谱、买菜清单及周日备菜流程的完整方案。支持减脂、增肌、控糖等多种目标，并自动生成可交互的 HTML 看板与 Markdown 文档，帮助用户高效执行健康饮食计划。",
    "author": "宛月",
    "folder": "weekly-meal-planner",
    "zip": "resources/skill-kit/packs/035-weekly-meal-planner.zip",
    "page": "resources/skill-kit/index.html#poju-035"
  },
  {
    "n": 36,
    "id": "poju-036",
    "name": "fairy-tale-writer",
    "cat": "写作",
    "brief": "童话故事创作家。用户给出一句话想法/模糊创意，创作出完整的世界经典童话风格的原创故事——格林童话的节奏骨架 + 安徒生童话的情感细节，充满童趣、画面感强，适合朗读，并把教育意义隐性植入情节而非说教。支持睡前故事、亲子共读、课堂教材、有声/绘本脚本等场景。触发词：写个童话、编个故事、童话故事、睡前故事、儿童故事、给宝宝/…",
    "author": "宛月",
    "folder": "fairy-tale-writer",
    "zip": "resources/skill-kit/packs/036-fairy-tale-writer.zip",
    "page": "resources/skill-kit/index.html#poju-036"
  },
  {
    "n": 37,
    "id": "poju-037",
    "name": "团队培训大纲设计助手",
    "cat": "学习教育",
    "brief": "团队培训大纲设计助手，根据受众、目标和约束设计分层课程大纲、课时、练习与考核，并给出可落地的排期。适用于新人入职、技术升级、项目开工及管理协作等场景，帮助制定可执行的培训计划。",
    "author": "㊣儿八经小青年",
    "folder": "团队培训大纲设计助手",
    "zip": "resources/skill-kit/packs/037-团队培训大纲设计助手.zip",
    "page": "resources/skill-kit/index.html#poju-037"
  },
  {
    "n": 38,
    "id": "poju-038",
    "name": "程序错误排查助手",
    "cat": "开发运维",
    "brief": "程序错误排查助手，根据报错、日志和复现步骤定位根因，给出证据链、最小修复方向和回归验证，禁止未取证就改代码。适用于开发联调、测试缺陷、生产告警等场景，提供结构化的排查记录输出规范。",
    "author": "㊣儿八经小青年",
    "folder": "程序错误排查助手",
    "zip": "resources/skill-kit/packs/038-程序错误排查助手.zip",
    "page": "resources/skill-kit/index.html#poju-038"
  },
  {
    "n": 39,
    "id": "poju-039",
    "name": "程序交付清单助手",
    "cat": "开发运维",
    "brief": "程序交付清单助手，按项目类型（如 Web、App、小程序）和阶段（提测、预发、上线、结项）生成详细的上线/验收/移交清单。覆盖构建产物、配置密钥、数据迁移、权限账号、测试质量、监控告警、文档培训及回滚应急等关键领域。支持区分阻断项与非阻断项，明确责任角色与验收证据要求，确保交付过程规范、可追溯，避免上线前遗漏关键事项。",
    "author": "㊣儿八经小青年",
    "folder": "程序交付清单助手",
    "zip": "resources/skill-kit/packs/039-程序交付清单助手.zip",
    "page": "resources/skill-kit/index.html#poju-039"
  },
  {
    "n": 40,
    "id": "poju-040",
    "name": "程序需求拆解助手",
    "cat": "开发运维",
    "brief": "程序需求拆解助手，把笼统需求拆成模块、用户故事、验收标准和迭代切片，标出依赖、缺口和范围外项。适用于立项、迭代规划、需求评审等场景，帮助补齐角色、场景、规则、异常和数据，减少开发过程中的沟通成本。",
    "author": "㊣儿八经小青年",
    "folder": "程序需求拆解助手",
    "zip": "resources/skill-kit/packs/040-程序需求拆解助手.zip",
    "page": "resources/skill-kit/index.html#poju-040"
  },
  {
    "n": 41,
    "id": "poju-041",
    "name": "程序测试用例生成助手",
    "cat": "开发运维",
    "brief": "程序测试用例生成助手，根据需求、接口或代码生成功能、边界、异常与回归用例，输出可执行的用例表和优先级。核心能力涵盖从需求/原型/接口中提取规则，运用等价类、边界值、判定表等方法设计用例，并按 P0/P1/P2 分级输出包含前置、步骤、数据、期望的表格。支持正常流、替代流、权限矩阵及回归影响分析，确保每条用例具备可执行性…",
    "author": "㊣儿八经小青年",
    "folder": "程序测试用例生成助手",
    "zip": "resources/skill-kit/packs/041-程序测试用例生成助手.zip",
    "page": "resources/skill-kit/index.html#poju-041"
  },
  {
    "n": 42,
    "id": "poju-042",
    "name": "程序数据库设计助手",
    "cat": "开发运维",
    "brief": "程序数据库设计助手，根据业务需求输出概念模型、表结构、主键索引、约束与演进建议，并标注性能与一致性取舍。支持新系统建库、需求变更评估及性能前置检查，优先确保正确性与可演进性。",
    "author": "㊣儿八经小青年",
    "folder": "程序数据库设计助手",
    "zip": "resources/skill-kit/packs/042-程序数据库设计助手.zip",
    "page": "resources/skill-kit/index.html#poju-042"
  },
  {
    "n": 43,
    "id": "poju-043",
    "name": "程序合同风险审查助手",
    "cat": "工具",
    "brief": "程序合同风险审查助手，面向接单开发者、乙方项目经理及甲方信息化负责人，提供软件开发/实施/运维合同的风险分析服务。核心功能包括：1. 条款拆解：自动识别开发、采购、SaaS 等合同类型，提取范围、交付物、验收、付款、IP、保密、违约等关键条款；2. 风险分级：将风险划分为红（严重亏损/无限责任）、黄（可谈判）、绿（常规…",
    "author": "㊣儿八经小青年",
    "folder": "程序合同风险审查助手",
    "zip": "resources/skill-kit/packs/043-程序合同风险审查助手.zip",
    "page": "resources/skill-kit/index.html#poju-043"
  },
  {
    "n": 44,
    "id": "poju-044",
    "name": "程序成本效益分析助手",
    "cat": "工具",
    "brief": "程序成本效益分析助手，帮助决策者判断系统是否值得做、何时做及自研还是外购。核心能力包括：1. 成本拆解（一次性、持续性、隐性成本）；2. 收益量化（增收、降本、时效等，含置信度）；3. 指标计算（TCO、ROI、回收期，支持乐观/基准/悲观三档情景）；4. 方案对比（做/不做/MVP/自研vs外购）；5. 决策建议（推…",
    "author": "㊣儿八经小青年",
    "folder": "程序成本效益分析助手",
    "zip": "resources/skill-kit/packs/044-程序成本效益分析助手.zip",
    "page": "resources/skill-kit/index.html#poju-044"
  },
  {
    "n": 45,
    "id": "poju-045",
    "name": "程序开发工期评估助手",
    "cat": "开发运维",
    "brief": "程序开发工期评估助手，面向项目经理、技术负责人及接单开发者，提供科学的软件项目排期方案。核心功能包括：1. 工作分解（WBS）：按功能模块、接口、测试等维度拆包，识别外部依赖；2. 三点估算：计算乐观/正常/悲观工期，得出期望工期；3. 产能与关键路径分析：区分人天与日历天数，识别并行与串行任务；4. 风险与缓冲管理：…",
    "author": "㊣儿八经小青年",
    "folder": "程序开发工期评估助手",
    "zip": "resources/skill-kit/packs/045-程序开发工期评估助手.zip",
    "page": "resources/skill-kit/index.html#poju-045"
  },
  {
    "n": 46,
    "id": "poju-046",
    "name": "程序代码审查助手",
    "cat": "开发运维",
    "brief": "程序代码审查助手，按正确性、可维护性、安全与测试完整性审查变更，输出分级意见和必须修复项，不扩 scope 到无关重构。适用于 Pull Request 审查、提交前自审及外包代码验收，聚焦本次改动风险，提供严重/重要/建议三级反馈，确保代码质量与安全合规。",
    "author": "㊣儿八经小青年",
    "folder": "程序代码审查助手",
    "zip": "resources/skill-kit/packs/046-程序代码审查助手.zip",
    "page": "resources/skill-kit/index.html#poju-046"
  },
  {
    "n": 47,
    "id": "poju-047",
    "name": "项目报价助手",
    "cat": "工具",
    "brief": "项目报价助手是一款专为开发者、设计师和自由职业者打造的效率工具。它能深入解析项目需求，自动评估开发工时（提供乐观/正常/悲观三档），精确核算人力与固定成本，并据此给出保守、标准及溢价三种报价区间。此外，该助手还提供分期付款建议和关键合同要点（如范围定义、知识产权、验收流程等），帮助用户在接单时做出合理定价并规避风险，提…",
    "author": "㊣儿八经小青年",
    "folder": "项目报价助手",
    "zip": "resources/skill-kit/packs/047-项目报价助手.zip",
    "page": "resources/skill-kit/index.html#poju-047"
  },
  {
    "n": 48,
    "id": "poju-048",
    "name": "旅行规划助手",
    "cat": "工具",
    "brief": "旅行行程规划助手是一款实用的自动化工具，旨在帮助用户快速制定详尽的旅行计划。通过输入目的地、天数、预算及兴趣偏好，该 Skill 能够自动生成包含每日时间安排（上午/中午/下午/晚上）、交通建议、餐饮推荐及费用估算的完整行程草案。此外，它还能自动补齐签证、天气、货币、通讯等出发前的必要检查清单，并提供当地风俗、避坑指南…",
    "author": "㊣儿八经小青年",
    "folder": "旅行规划助手",
    "zip": "resources/skill-kit/packs/048-旅行规划助手.zip",
    "page": "resources/skill-kit/index.html#poju-048"
  },
  {
    "n": 49,
    "id": "poju-049",
    "name": "gpt-image-2 生图",
    "cat": "设计",
    "brief": "Breakout 对话生图：通过 Breakout/Wenwen 的 OpenAI 兼容对话接口调用 gpt-image-2 模型生成图片。支持自定义 Bearer API Key、提示词（文本或文件）、归档响应、提取并下载图片 URL、base64 解码，输出统一管理。",
    "author": "雪见RPA+AI",
    "folder": "gpt-image-2 生图",
    "zip": "resources/skill-kit/packs/049-gpt-image-2-生图.zip",
    "page": "resources/skill-kit/index.html#poju-049"
  },
  {
    "n": 50,
    "id": "poju-050",
    "name": "周报速写",
    "cat": "工具",
    "brief": "这是一个通用的周报生成助手，适用于运营、销售、产品、研发等各类岗位。它通过四步流水线（成果提炼、价值呈现、问题闭环、管理视角），将原始工作记录转化为管理者可读的结构化报告。支持自动过滤流水账，强制要求数据支撑和价值关联，确保输出专业、客观且重点突出。",
    "author": "㊣儿八经小青年",
    "folder": "周报速写",
    "zip": "resources/skill-kit/packs/050-周报速写.zip",
    "page": "resources/skill-kit/index.html#poju-050"
  },
  {
    "n": 51,
    "id": "poju-051",
    "name": "短剧结构显微镜",
    "cat": "音视频",
    "brief": "面向短剧编剧与创作者的逐集结构拆解工具。输入本地正片后，自动执行抽帧、语音转写，并通过画面与字幕交叉校验，逐集拆解剧情推进、节奏卡点、钩子设计与可复用叙事手法。支持断点续跑与跨平台运行，帮助分析短剧叙事有效性。",
    "author": "糖醋大米",
    "folder": "短剧结构显微镜",
    "zip": "resources/skill-kit/packs/051-短剧结构显微镜.zip",
    "page": "resources/skill-kit/index.html#poju-051"
  },
  {
    "n": 52,
    "id": "poju-052",
    "name": "杠杆skills",
    "cat": "学习教育",
    "brief": "这是一个基于「支点与杠杆」方法论的个人成长辅助工具。它帮助用户通过「人生回报 ≈ 支点 × 杠杆率」公式，诊断自身在技能、信用、系统三大支点上的底盘情况，并据此从劳动力、资本、媒介、人脉、空间套利、AI资产六大杠杆中选择合适的放大器。Skill 内置标准化的诊断流程、输出模板及低成本实验设计指南，旨在引导用户先打磨支点…",
    "author": "小机AI智能体",
    "folder": "杠杆skills",
    "zip": "resources/skill-kit/packs/052-杠杆skills.zip",
    "page": "resources/skill-kit/index.html#poju-052"
  },
  {
    "n": 53,
    "id": "poju-053",
    "name": "连续长海报生成 continuous-long-poster",
    "cat": "设计",
    "brief": "连续长海报自动生成与拼接工具。支持读取文章、PDF等素材，通过OpenAI兼容API、OPC、即梦CLI或火山Ark CLI生成连续分段图，并利用本地Python脚本自动执行裁切、重叠、羽化与融合，最终导出完整长海报。适用于时间轴、课程图解、产品长页等场景。",
    "author": "Roths Yang",
    "folder": "连续长海报生成 continuous-long-poster",
    "zip": "resources/skill-kit/packs/053-连续长海报生成-continuous-long-poster.zip",
    "page": "resources/skill-kit/index.html#poju-053"
  },
  {
    "n": 54,
    "id": "poju-054",
    "name": "小红书跨境CRS获客系统",
    "cat": "写作",
    "brief": "小红书 CRS 内容助手，专为跨境 CRS 与境外券商税务汇算账号设计。支持从零生成、二创参考内容或优化现有稿件，适用于用户给出选题、真实提问、评论或通知场景。系统能自动生成标题、封面文案、正文（含轮播结构）及结尾互动问题，重点在于将复杂的账单和税务概念转化为通俗易懂的知识型内容，确保事实准确且符合平台规范。",
    "author": "飞锅✨",
    "folder": "小红书跨境CRS获客系统",
    "zip": "resources/skill-kit/packs/054-小红书跨境CRS获客系统.zip",
    "page": "resources/skill-kit/index.html#poju-054"
  },
  {
    "n": 55,
    "id": "poju-055",
    "name": "小红书对标笔记分析skill",
    "cat": "数据分析",
    "brief": "一款专注于小红书内容策略分析的辅助工具。它能对单篇或批量对标笔记进行深度拆解，涵盖选题点击、开篇留存、价值信任、情绪需求、互动评论及商品转化等六个核心层级。通过区分近期信号与长期规律，提炼出可迁移的内容机制，并为下一轮创作提供具体的单变量测试方向。适用于需要快速理解爆款逻辑、优化自身内容策略的用户，帮助从数据表象洞察底…",
    "author": "飞锅✨",
    "folder": "小红书对标笔记分析skill",
    "zip": "resources/skill-kit/packs/055-小红书对标笔记分析skill.zip",
    "page": "resources/skill-kit/index.html#poju-055"
  },
  {
    "n": 56,
    "id": "poju-056",
    "name": "小红书投流数据分析skill",
    "cat": "数据分析",
    "brief": "本 Skill 专为小红书商业笔记投流设计，旨在帮助用户将后台数据转化为明确的投放决策。它通过分析投流准备度、计划消耗、转化漏斗、获客成本、后台 ROI 与最终利润，判断当前策略应暂停、优化后复测、保留还是逐步放量。适用于用户提供千帆或推广后台截图、计划数据、经营成本表等场景，解决“商笔怎么投”、“ROI多少才不亏”等…",
    "author": "飞锅✨",
    "folder": "小红书投流数据分析skill",
    "zip": "resources/skill-kit/packs/056-小红书投流数据分析skill.zip",
    "page": "resources/skill-kit/index.html#poju-056"
  },
  {
    "n": 57,
    "id": "poju-057",
    "name": "小红书好评助手",
    "cat": "写作",
    "brief": "小红书商品评价助手是一款专注于电商运营的内容生成工具。它支持三种核心模式：一是自动生成口语化、像真实买家分享的商品好评草稿；二是根据产品属性设计“好评有礼”活动方案，包括赠品建议、参与路径及执行文案；三是结合客户聊天记录，智能判断客户状态并生成个性化的引导好评话术。该工具严格遵循合规边界，不虚构事实、不冒充消费者刷单，…",
    "author": "飞锅✨",
    "folder": "小红书好评助手",
    "zip": "resources/skill-kit/packs/057-小红书好评助手.zip",
    "page": "resources/skill-kit/index.html#poju-057"
  },
  {
    "n": 58,
    "id": "poju-058",
    "name": "定制化旅行攻略skill",
    "cat": "工具",
    "brief": "本Skill旨在构建高度定制化的旅行行程规划。它通过渐进式交互收集用户的核心约束（如日期、交通方式、偏好）和偏好细节，并结合当前季节、交通管制、景区政策等实时事实进行校验。生成的攻略包含清晰的每日日程、里程与车程估算、住宿与餐饮建议、景点取舍理由、拍照打卡点以及详细的行前检查清单。特别针对自驾场景提供顺时针/逆时针路线…",
    "author": "飞锅✨",
    "folder": "定制化旅行攻略skill",
    "zip": "resources/skill-kit/packs/058-定制化旅行攻略skill.zip",
    "page": "resources/skill-kit/index.html#poju-058"
  },
  {
    "n": 59,
    "id": "poju-059",
    "name": "小红书测试品封面生成",
    "cat": "设计",
    "brief": "为小红书虚拟产品或待验证测试品生成独立的 3:4 笔记封面。支持新品探索、单变量封面测试、参考图二创和已有封面迭代，并保存封面测试记录。适用于用户说“给测试品做封面”“生成几张小红书测试封面”“参考这个封面二创”“做封面AB测试”“为虚拟产品测点击”等场景；不用于商品详情页整套设计、纯文字长图正文或只分析现有封面数据。",
    "author": "飞锅✨",
    "folder": "小红书测试品封面生成",
    "zip": "resources/skill-kit/packs/059-小红书测试品封面生成.zip",
    "page": "resources/skill-kit/index.html#poju-059"
  },
  {
    "n": 60,
    "id": "poju-060",
    "name": "小红书笔记数据分析助手",
    "cat": "数据分析",
    "brief": "小红书笔记数据分析助手，旨在帮助用户分析单篇或多篇笔记的阅读、互动、涨粉和商品转化数据。通过校验指标口径、定位流量漏斗问题（如收录分发、点击率、内容消费、互动涨粉、商品转化等层级），输出按优先级排列的内容迭代与单变量测试方案。适用于用户提供数据截图、后台导出、表格或口述数据后的场景，帮助解决“为什么没流量”、“哪篇表现…",
    "author": "飞锅✨",
    "folder": "小红书笔记数据分析助手",
    "zip": "resources/skill-kit/packs/060-小红书笔记数据分析助手.zip",
    "page": "resources/skill-kit/index.html#poju-060"
  },
  {
    "n": 61,
    "id": "poju-061",
    "name": "小红书选题扩展助手",
    "cat": "写作",
    "brief": "小红书选题扩展助手：将商品、赛道、账号定位或种子选题扩展成差异明确、可直接执行的小红书选题矩阵。支持自动判断输入类型（商品/种子/赛道/竞品），通过人群、场景、问题、结果、决策、表达六个维度进行扩展。内置去重与真实性检查机制，确保不虚构产品能力或蹭无关流量。提供基于用户相关性、搜索意图、新鲜度、素材可得性和转化距离的轻…",
    "author": "飞锅✨",
    "folder": "小红书选题扩展助手",
    "zip": "resources/skill-kit/packs/061-小红书选题扩展助手.zip",
    "page": "resources/skill-kit/index.html#poju-061"
  },
  {
    "n": 62,
    "id": "poju-062",
    "name": "跨平台素材归档",
    "cat": "自动化",
    "brief": "link-to-inbox 是一款跨平台链接自动归档工具，支持公众号、小红书、抖音、快手、B站、视频号、TikTok、YouTube 和知识星球等 9 个平台。它通过 dousnap 统一入口或 zsxq-cli 直连 API 抓取内容，自动下载附件并生成带标准 frontmatter 的 Markdown 文件，存入…",
    "author": "Sheldon",
    "folder": "跨平台素材归档",
    "zip": "resources/skill-kit/packs/062-跨平台素材归档.zip",
    "page": "resources/skill-kit/index.html#poju-062"
  },
  {
    "n": 63,
    "id": "poju-063",
    "name": "微课接单到交付全流程SOP",
    "cat": "学习教育",
    "brief": "一套经过100+实战单验证的微课接单到交付完整流程SOP。涵盖从赛制分析、需求沟通、教学设计、课件制作、逐字稿撰写、客户录制到视频合成的7步闭环。每步附核心原则和防坑要点，如全程打水印防白嫖、先试录再全录等，帮助宝妈、教师及自由职业者规范交付流程，提高接单效率与成功率，避免返工风险。",
    "author": "Helen",
    "folder": "微课接单到交付全流程SOP",
    "zip": "resources/skill-kit/packs/063-微课接单到交付全流程SOP.zip",
    "page": "resources/skill-kit/index.html#poju-063"
  },
  {
    "n": 64,
    "id": "poju-064",
    "name": "品牌视觉识别（VI）手册设计",
    "cat": "设计",
    "brief": "本技能提供一套完整的品牌视觉识别（VI）手册设计工作流。从标志变体、辅助图形到真实场景应用规范，指导用户产出 15–25 页统一 16:9 比例、双语标题、视觉语言一致的标准化手册页面。内置 Python 脚本可自动生成 HTML 预览画廊供客户审阅，支持多轮迭代精修以确保视觉保真度与跨页一致性。适用于需要制作品牌手册…",
    "author": "Roths Yang",
    "folder": "品牌视觉识别（VI）手册设计",
    "zip": "resources/skill-kit/packs/064-品牌视觉识别-VI-手册设计.zip",
    "page": "resources/skill-kit/index.html#poju-064"
  },
  {
    "n": 65,
    "id": "poju-065",
    "name": "小说改短剧开发助手",
    "cat": "写作",
    "brief": "这是一个专业的小说改短剧开发助手，以“工作台”模式推进创作流程。它能读取小说或网文材料，进行素材诊断并区分事实边界。在确认项目形态（如一部完整短剧或多季改编）后，自动生成包含IP诊断、故事发动机、动态人物表等内容的七件套试制包。此外，它还支持生成分集大纲和单集正文，具备严格的连续性检查机制，确保人物关系、道具伏笔和剧情…",
    "author": "糖醋大米",
    "folder": "小说改短剧开发助手",
    "zip": "resources/skill-kit/packs/065-小说改短剧开发助手.zip",
    "page": "resources/skill-kit/index.html#poju-065"
  },
  {
    "n": 66,
    "id": "poju-066",
    "name": "短篇小说导语",
    "cat": "写作",
    "brief": "短篇小说导语生成器。为一篇或多篇短篇小说（全文、大纲或设定）批量生成高转化导语/简介：按六大钩子公式产出多条候选，内置平台字数与违规词校验。适用于网文平台发布前的简介撰写（番茄小说、七猫、起点、晋江、知乎盐选等），触发场景包括\"写导语\"\"写简介\"\"优化简介\"\"批量生成导语\"\"书籍详情页文案\"。",
    "author": "兔女财",
    "folder": "短篇小说导语",
    "zip": "resources/skill-kit/packs/066-短篇小说导语.zip",
    "page": "resources/skill-kit/index.html#poju-066"
  },
  {
    "n": 67,
    "id": "poju-067",
    "name": "爆款脑洞生成器",
    "cat": "写作",
    "brief": "爆款脑洞生成器是一款专为短视频（抖音/快手/视频号/小红书）及自媒体创作者设计的创意辅助工具。它基于 12 种成熟的脑洞公式（如反差冲突、跨界嫁接等）和爆款钩子模板，帮助用户快速生成高质量的选题方案。 核心功能包括： 1. **结构化输出**：为每个脑洞生成包含标题、黄金 3 秒钩子、脚本梗概、目标情绪及爆款指数评分…",
    "author": "兔女财",
    "folder": "爆款脑洞生成器",
    "zip": "resources/skill-kit/packs/067-爆款脑洞生成器.zip",
    "page": "resources/skill-kit/index.html#poju-067"
  },
  {
    "n": 68,
    "id": "poju-068",
    "name": "番茄小说爆款书名",
    "cat": "写作",
    "brief": "专为番茄小说等免费阅读平台设计的爆款书名生成助手。覆盖男频（都市神豪、高武、玄幻）与女频（豪门、年代、穿书）等多类题材。内置八大爆款书名公式、高频钩子词库及分题材句式模板。提供自动化 Python 脚本对候选书名进行多维度打分排序，并附带平台审核红线自检清单，帮助用户快速产出高点击率、合规且具吸引力的书名。",
    "author": "兔女财",
    "folder": "番茄小说爆款书名",
    "zip": "resources/skill-kit/packs/068-番茄小说爆款书名.zip",
    "page": "resources/skill-kit/index.html#poju-068"
  },
  {
    "n": 69,
    "id": "poju-069",
    "name": "西幻风格脑洞/灵感生成",
    "cat": "写作",
    "brief": "西幻风格脑洞/灵感生成器。专为西方奇幻（西幻）题材创作设计，适用于构思小说、TRPG 跑团设定、游戏世界观及角色剧情。核心功能包括：通过 scripts/spark.py 脚本进行随机灵感轰炸，快速产出包含核心概念、冲突与反转的设定种子；利用 references 下的素材库（characters, plots, wo…",
    "author": "兔女财",
    "folder": "西幻风格脑洞_灵感生成",
    "zip": "resources/skill-kit/packs/069-西幻风格脑洞_灵感生成.zip",
    "page": "resources/skill-kit/index.html#poju-069"
  },
  {
    "n": 70,
    "id": "poju-070",
    "name": "番茄大纲",
    "cat": "写作",
    "brief": "一款专为番茄小说平台设计的网文大纲生成助手。它能根据用户提供的创意或题材方向，自动生成完整的三层大纲：总纲（含书名候选、简介、金手指设定、人物小传）、分卷大纲（主线冲突、卷末高潮）以及章节细纲（核心事件、爽点/卡点设计、章末钩子）。内置番茄平台节奏规范、审核红线及热门题材标签，确保大纲符合平台推荐算法与读者偏好，帮助作…",
    "author": "兔女财",
    "folder": "番茄大纲",
    "zip": "resources/skill-kit/packs/070-番茄大纲.zip",
    "page": "resources/skill-kit/index.html#poju-070"
  },
  {
    "n": 71,
    "id": "poju-071",
    "name": "小说核心梗",
    "cat": "写作",
    "brief": "小说核心梗设计与提炼工具。适用于网文创作场景：从零设计一部小说的核心梗（高概念卖点）、从已有小说文本或简介中提炼核心梗、诊断并优化现有核心梗是否够\"炸\"。当用户提到\"核心梗\"、\"梗\"、\"卖点\"、\"高概念\"、\"一句话简介\"、\"书名方向\"、\"开书策划\"、\"选题策划\"等网文创作需求时使用本技能。覆盖番茄、起点、晋江、七猫等主…",
    "author": "兔女财",
    "folder": "小说核心梗",
    "zip": "resources/skill-kit/packs/071-小说核心梗.zip",
    "page": "resources/skill-kit/index.html#poju-071"
  },
  {
    "n": 72,
    "id": "poju-072",
    "name": "建筑工程专利申请书",
    "cat": "写作",
    "brief": "建筑工程领域专利申请书自动撰写工具。当用户需要撰写、生成或完善建筑工程相关的专利申请文件（发明专利或实用新型专利的请求书、说明书、权利要求书、说明书摘要、附图说明）时使用此技能。适用场景包括：建筑施工方法与工艺、建筑结构与构件、装配式建筑、绿色建材、地基基础与基坑工程、施工设备与机具、建筑节能与智能化（BIM/智慧工地…",
    "author": "兔女财",
    "folder": "建筑工程专利申请书",
    "zip": "resources/skill-kit/packs/072-建筑工程专利申请书.zip",
    "page": "resources/skill-kit/index.html#poju-072"
  },
  {
    "n": 73,
    "id": "poju-073",
    "name": "小说批量部署",
    "cat": "工具",
    "brief": "小说批量部署：将整本 TXT 小说自动切分为标准章节文件，按番茄、起点、晋江等主流平台的格式与字数要求规范导出。支持自定义正则切章、多编码自动识别、字数异常检测及生成部署清单，辅助作者高效完成批量发布准备。",
    "author": "兔女财",
    "folder": "小说批量部署",
    "zip": "resources/skill-kit/packs/073-小说批量部署.zip",
    "page": "resources/skill-kit/index.html#poju-073"
  },
  {
    "n": 74,
    "id": "poju-074",
    "name": "定时备份",
    "cat": "自动化",
    "brief": "这是一个专为 Windows 环境设计的定时备份自动化技能。它通过调用 PowerShell 脚本 `backup.ps1` 实现文件夹的自动备份，支持一次性或周期性执行。提供两种备份模式：`mirror`（镜像模式，保持目标与源一致）和 `snapshot`（快照模式，生成带时间戳的独立副本以便恢复）。用户可配置备份…",
    "author": "兔女财",
    "folder": "定时备份",
    "zip": "resources/skill-kit/packs/074-定时备份.zip",
    "page": "resources/skill-kit/index.html#poju-074"
  },
  {
    "n": 75,
    "id": "poju-075",
    "name": "小说内容生成",
    "cat": "写作",
    "brief": "一款专为小说创作者设计的辅助技能，提供从构思到成稿的完整工作流。支持玄幻、言情、悬疑等多种主流题材，涵盖世界观构建、角色设计、大纲规划、章节生成及一致性维护。内置专业参考文档指导叙事技巧与节奏控制，并附带自动化脚本管理章节文件、追踪伏笔状态及导出成品，助力高效创作高质量文学作品。",
    "author": "兔女财",
    "folder": "小说内容生成",
    "zip": "resources/skill-kit/packs/075-小说内容生成.zip",
    "page": "resources/skill-kit/index.html#poju-075"
  },
  {
    "n": 76,
    "id": "poju-076",
    "name": "微习惯行动设计",
    "cat": "学习教育",
    "brief": "基于福格行为模型（B=MAP）的行为拆解助手。当用户面临习惯养成困难、半途而废或无法坚持时，本 Skill 自动触发。它不依赖意志力说教，而是通过动机、能力、提示三要素精准诊断行为断环，并利用微习惯法设计可秒执行的微小行动、锚点提示及即时庆祝方案。旨在以科学的行为设计解决执行难题，提供不灌鸡汤、不归咎人格的可落地策略。",
    "author": "宛月",
    "folder": "微习惯行动设计",
    "zip": "resources/skill-kit/packs/076-微习惯行动设计.zip",
    "page": "resources/skill-kit/index.html#poju-076"
  },
  {
    "n": 77,
    "id": "poju-077",
    "name": "个性化学习规划",
    "cat": "学习教育",
    "brief": "Learning Coach 是一款专注于高效学习的辅助工具。它通过联网检索真实课程资料来验证学习路径的可行性，并根据用户的背景、目标和可用时间量身定制详细的学习蓝图（包括知识树、周计划和日任务卡）。此外，Skill 支持在用户确认后创建每日推送、打卡及周复盘等自动化提醒任务，帮助用户克服惰性，确保持续学习并最终达成目…",
    "author": "宛月",
    "folder": "个性化学习规划",
    "zip": "resources/skill-kit/packs/077-个性化学习规划.zip",
    "page": "resources/skill-kit/index.html#poju-077"
  },
  {
    "n": 78,
    "id": "poju-078",
    "name": "图书知识蒸馏",
    "cat": "学习教育",
    "brief": "Book Distiller 是一款高效的图书内容蒸馏工具。它能将电子书全文或读书笔记转化为「全能蒸馏包」，包含一句话定位、核心论点、思维模型、金句摘录及行动清单。支持 PDF/EPUB 全文通读与笔记整理两种模式，并针对不同书类（如个人成长、商业、小说等）提供差异化的提炼角度。产出内容可直接用于多平台发布，帮助用户从…",
    "author": "宛月",
    "folder": "图书知识蒸馏",
    "zip": "resources/skill-kit/packs/078-图书知识蒸馏.zip",
    "page": "resources/skill-kit/index.html#poju-078"
  },
  {
    "n": 79,
    "id": "poju-079",
    "name": "小红书低粉爆款挖掘",
    "cat": "数据分析",
    "brief": "这是一个用于小红书内容调研的自动化工具，专门帮助创作者和运营人员挖掘“低粉爆款”案例。它支持两种工作模式：一是通过配置 TikHub API Key 自动抓取搜索结果并筛选出粉丝少但互动高的笔记；二是允许用户手动粘贴笔记标题、互动数据和作者信息，由系统进行分析。技能内置了详细的数据清洗规则（如处理“万”单位粉丝数）、爆…",
    "author": "大鹏",
    "folder": "小红书低粉爆款挖掘",
    "zip": "resources/skill-kit/packs/079-小红书低粉爆款挖掘.zip",
    "page": "resources/skill-kit/index.html#poju-079"
  },
  {
    "n": 80,
    "id": "poju-080",
    "name": "小红书评论需求洞察",
    "cat": "数据分析",
    "brief": "从小红书评论中提炼用户需求，适合分析高频问题、购买顾虑、真实使用场景、反对意见、求教程和下一篇内容机会。支持笔记链接、笔记 ID、关键词检索评论或用户粘贴评论文本。",
    "author": "大鹏",
    "folder": "小红书评论需求洞察",
    "zip": "resources/skill-kit/packs/080-小红书评论需求洞察.zip",
    "page": "resources/skill-kit/index.html#poju-080"
  },
  {
    "n": 81,
    "id": "poju-081",
    "name": "小红书对标账号拆解",
    "cat": "数据分析",
    "brief": "一款专注于小红书对标账号深度拆解的分析工具。支持通过账号主页链接、用户 ID 或粘贴资料进行数据采集与分析。核心功能包括： 1. **多维数据采集**：自动获取账号基础信息（昵称、简介、粉丝数）及近期笔记互动数据。 2. **内容策略诊断**：将笔记划分为门面、拉新、信任三类，分析账号定位与人设构建。 3. **爆款…",
    "author": "大鹏",
    "folder": "小红书对标账号拆解",
    "zip": "resources/skill-kit/packs/081-小红书对标账号拆解.zip",
    "page": "resources/skill-kit/index.html#poju-081"
  },
  {
    "n": 82,
    "id": "poju-082",
    "name": "四人私董会决策咨询",
    "cat": "学习教育",
    "brief": "这是一个模拟私董会形式的专家咨询 Skill。它整合了巴菲特、比尔·盖茨、马斯克和乔布斯四位商业领袖的思维模型与语言风格，为用户提供沉浸式的决策支持体验。Skill 严格遵循私董会的标准流程：从确认案主问题开始，经过三轮由不同幕僚依次提出的深度提问（每问必待用户回答），到案主反问环节，最后由幕僚提供包含名言、感受、定性…",
    "author": "AI Jackson",
    "folder": "四人私董会决策咨询",
    "zip": "resources/skill-kit/packs/082-四人私董会决策咨询.zip",
    "page": "resources/skill-kit/index.html#poju-082"
  },
  {
    "n": 83,
    "id": "poju-083",
    "name": "短视频爆款因子分析专家",
    "cat": "写作",
    "brief": "短视频爆款因子分析专家。当用户提供短视频文案时，从整体爆款特征、选题与内容价值、黄金开头三秒钩子、文案结构与节奏、语言风格与共鸣表达五大维度深度拆解爆款潜力。输出结构化分析报告，引用原文、标注模型应用情况，并给出具体可行的优化建议，帮助创作者提升传播力。",
    "author": "AI Jackson",
    "folder": "短视频爆款因子分析专家",
    "zip": "resources/skill-kit/packs/083-短视频爆款因子分析专家.zip",
    "page": "resources/skill-kit/index.html#poju-083"
  },
  {
    "n": 84,
    "id": "poju-084",
    "name": "微信公众号_洋哥爆款标题生成器",
    "cat": "写作",
    "brief": "微信公众号爆款标题定制专家。当用户准备好公众号文章内容时，可根据“流量关键词+数字+冲突悬疑+动词+情绪钩子”公式及4类模板，输出10个20字以内、带打分与爆款元素标注的备选标题。适用于需要提升文章点击率和传播力的场景。",
    "author": "AI Jackson",
    "folder": "微信公众号_洋哥爆款标题生成器",
    "zip": "resources/skill-kit/packs/084-微信公众号_洋哥爆款标题生成器.zip",
    "page": "resources/skill-kit/index.html#poju-084"
  },
  {
    "n": 85,
    "id": "poju-085",
    "name": "AI短剧全流程 · 创作工作流引擎",
    "cat": "写作",
    "brief": "AI短剧全流程创作工作流引擎：整合选题与IP评估、小说筛选、故事/人物/情节结构化分析、剧本创作与策划、多维度评估打分、知识检索与结果整合等模块。通过编排式工作流协调多个子智能体，把小说或创意转化为竖屏短剧策划、剧本与结构化分析报告，覆盖竖屏短剧、小说改编、漫剧等题材。提供从宏观建构到单集剧本创作的完整方法论与模板。",
    "author": "一只阿木木",
    "folder": "AI短剧全流程 · 创作工作流引擎",
    "zip": "resources/skill-kit/packs/085-AI短剧全流程-创作工作流引擎.zip",
    "page": "resources/skill-kit/index.html#poju-085"
  },
  {
    "n": 86,
    "id": "poju-086",
    "name": "爆款短剧剧本一键生成",
    "cat": "音视频",
    "brief": "面向零基础创作者的 AI 短剧与漫剧全流程导演工具。将创意、小说或文章一键转化为选题、角色资产（三视图与表情）、分集剧本、专业分镜、图片/视频提示词、画质风格方案及生成任务清单。内置爆款结构重构、相似风险检查与独立质检模块，支持竖屏短剧、动态漫画、武侠玄幻等多种题材。通过标准化的模板与校验脚本，确保角色一致性、叙事逻辑…",
    "author": "一只阿木木",
    "folder": "爆款短剧剧本一键生成",
    "zip": "resources/skill-kit/packs/086-爆款短剧剧本一键生成.zip",
    "page": "resources/skill-kit/index.html#poju-086"
  },
  {
    "n": 87,
    "id": "poju-087",
    "name": "A股年报下载",
    "cat": "数据分析",
    "brief": "A股年报下载 Skill 支持根据股票名称或代码、年份及报告类型（年报、半年报、一季报、三季报）检索并下载 A 股上市公司定期报告 PDF。覆盖沪市、深市、创业板、科创板及北交所。具备智能解析输入、自动过滤干扰项（如摘要、修订稿）、批量查询及文件完整性校验功能。返回公告标题、披露日期、文件链接及本地路径，适用于金融研究…",
    "author": "大鹏",
    "folder": "A股年报下载",
    "zip": "resources/skill-kit/packs/087-A股年报下载.zip",
    "page": "resources/skill-kit/index.html#poju-087"
  },
  {
    "n": 88,
    "id": "poju-088",
    "name": "深度复盘助手",
    "cat": "工具",
    "brief": "深度复盘助手是一款专业的反思引导工具，适用于个人周期、项目交付及关键事件的复盘场景。它通过结构化的四层追问法（事实、感受、判断、行动），帮助用户剥离流水账式的叙述，精准识别预期与实际的偏差，挖掘深层原因并规避常见认知陷阱。Skill 内置多种追问策略和输出模板，支持生成标准版或快速版复盘报告，确保每个改进动作都具备可执…",
    "author": "大鹏",
    "folder": "深度复盘助手",
    "zip": "resources/skill-kit/packs/088-深度复盘助手.zip",
    "page": "resources/skill-kit/index.html#poju-088"
  },
  {
    "n": 89,
    "id": "poju-089",
    "name": "短视频分镜优化",
    "cat": "音视频",
    "brief": "一款专注于短视频制作的辅助工具，能够将口播稿、文章段落、产品脚本或创意概念转化为可执行的分镜方案。它提供详细的镜头表，涵盖画面动作、构图、人物一致性锚点以及适用于图像和视频生成的具体提示词（含负向约束）。内置专业的镜头语言参考和质量检查清单，帮助用户优化竖屏视频素材的视觉表现和叙事节奏，提升内容生产效率。",
    "author": "大鹏",
    "folder": "短视频分镜优化",
    "zip": "resources/skill-kit/packs/089-短视频分镜优化.zip",
    "page": "resources/skill-kit/index.html#poju-089"
  },
  {
    "n": 90,
    "id": "poju-090",
    "name": "人物故事脚本优化",
    "cat": "写作",
    "brief": "这是一个专门用于优化人物故事短视频口播稿的 AI 助手。它不仅能对已有草稿进行润色，还能从零开始构建故事主线。核心功能包括：1. 严格的事实风险检查，区分已确认事实与需谨慎表述，杜绝编造名言、心理活动或未经证实的细节；2. 故事结构优化，提供反差、选择、误解等多种叙事模板，确保主线清晰、开头吸引人；3. 口播节奏调整，…",
    "author": "大鹏",
    "folder": "人物故事脚本优化",
    "zip": "resources/skill-kit/packs/090-人物故事脚本优化.zip",
    "page": "resources/skill-kit/index.html#poju-090"
  },
  {
    "n": 91,
    "id": "poju-091",
    "name": "生成个人网站",
    "cat": "设计",
    "brief": "这是一个用于生成可本地预览和打包的静态个人展示页的工具。它支持在线简历、作品集、个人主页等多种场景。用户只需提供个人信息、背景经历、作品和技能等数据，系统即可根据预设模板（如求职简历、开发者作品集、创作者主页）自动生成包含 HTML、CSS 和 JavaScript 的完整网站目录。此外，它还支持通过自然语言反馈进行样…",
    "author": "大鹏",
    "folder": "生成个人网站",
    "zip": "resources/skill-kit/packs/091-生成个人网站.zip",
    "page": "resources/skill-kit/index.html#poju-091"
  },
  {
    "n": 92,
    "id": "poju-092",
    "name": "职业能力测评",
    "cat": "工具",
    "brief": "基于行为证据的职业能力测评工具。支持根据简历、面试回答或项目复盘等材料，对沟通协作、逻辑分析、执行推进等维度进行评分。提供岗位匹配提示及可执行的短期提升计划，帮助求职者或职场人明确能力短板与发展方向。",
    "author": "大鹏",
    "folder": "职业能力测评",
    "zip": "resources/skill-kit/packs/092-职业能力测评.zip",
    "page": "resources/skill-kit/index.html#poju-092"
  },
  {
    "n": 93,
    "id": "poju-093",
    "name": "公众号文章排版",
    "cat": "设计",
    "brief": "一款专为微信公众号文章设计的排版工具。它支持多种预设主题（如清爽知识蓝、商务深青、科技暗色等），可根据文章类型自动匹配视觉风格。用户输入草稿后，Skill 会生成带有内联样式的 HTML 源码，并提供一个包含一键复制功能的浏览器预览页面，解决公众号编辑器不兼容直接粘贴 HTML 的痛点，实现高效、美观的文章发布。",
    "author": "大鹏",
    "folder": "公众号文章排版",
    "zip": "resources/skill-kit/packs/093-公众号文章排版.zip",
    "page": "resources/skill-kit/index.html#poju-093"
  },
  {
    "n": 94,
    "id": "poju-094",
    "name": "公众号账号诊断",
    "cat": "数据分析",
    "brief": "公众号账号健康度诊断工具。支持导入后台文章数据、阅读互动指标、用户画像及对标账号信息。系统依据内容表现（35分）、用户匹配（25分）、互动留存（25分）和运营稳定（15分）四大维度对账号进行综合评分。能够识别爆款与低效文章，分析读者定位偏差，并生成包含具体动作的30天优化计划。适用于需要基于数据驱动决策的公众号运营者，…",
    "author": "大鹏",
    "folder": "公众号账号诊断",
    "zip": "resources/skill-kit/packs/094-公众号账号诊断.zip",
    "page": "resources/skill-kit/index.html#poju-094"
  },
  {
    "n": 95,
    "id": "poju-095",
    "name": "需求澄清助手",
    "cat": "工具",
    "brief": "这款技能旨在帮助用户将模糊的想法、口头需求或初步设想，转化为清晰、可独立交付的任务契约。它通过多轮结构化提问，引导用户明确背景、目标、交付物、验收标准、范围边界及风险假设。适用于产品经理、运营人员及开发者在启动项目前统一认知、收敛需求，确保执行者能准确理解任务意图并高效完成工作。",
    "author": "大鹏",
    "folder": "需求澄清助手",
    "zip": "resources/skill-kit/packs/095-需求澄清助手.zip",
    "page": "resources/skill-kit/index.html#poju-095"
  },
  {
    "n": 96,
    "id": "poju-096",
    "name": "创业想法验证",
    "cat": "研究检索",
    "brief": "这是一个专业的创业想法验证助手。它帮助用户系统评估创业项目的可行性，核心功能包括：识别真实痛点与目标用户、分析现有替代方案与竞品格局、评估市场空间与付费意愿、计算加权市场机会评分，并设计低成本的最小验证实验（如访谈、着陆页测试、预售等）。输出结构化报告，包含结论（继续/调整/暂停/放弃）、置信度及具体行动建议，避免主观…",
    "author": "大鹏",
    "folder": "创业想法验证",
    "zip": "resources/skill-kit/packs/096-创业想法验证.zip",
    "page": "resources/skill-kit/index.html#poju-096"
  },
  {
    "n": 97,
    "id": "poju-097",
    "name": "文件整理助手",
    "cat": "工具",
    "brief": "一款安全的本地文件夹整理助手。支持按扩展名、名称关键词或自定义 JSON 规则对文件进行分类归档。提供扫描预览、用户确认执行及基于 manifest 的一键回滚功能，确保数据安全。内置多种常见文件类型默认规则，适用于下载目录、桌面及素材库等场景。",
    "author": "大鹏",
    "folder": "文件整理助手",
    "zip": "resources/skill-kit/packs/097-文件整理助手.zip",
    "page": "resources/skill-kit/index.html#poju-097"
  },
  {
    "n": 98,
    "id": "poju-098",
    "name": "简历岗位匹配优化",
    "cat": "写作",
    "brief": "对照目标岗位优化简历。用户提供简历、岗位说明、招聘链接或目标方向后，拆解岗位要求，判断经历证据是否命中，找出缺口、关键词和版式风险，并给出可直接替换到简历里的经历改写。",
    "author": "大鹏",
    "folder": "简历岗位匹配优化",
    "zip": "resources/skill-kit/packs/098-简历岗位匹配优化.zip",
    "page": "resources/skill-kit/index.html#poju-098"
  },
  {
    "n": 99,
    "id": "poju-099",
    "name": "多平台风险词检查",
    "cat": "工具",
    "brief": "多平台风险词检查：发布公众号、小红书、抖音内容前，自动检查标题、正文、口播稿等文案中的违禁词、极限词、虚假承诺及诱导转化风险。精准标出命中位置、风险等级及上下文原因，并提供最小改动版替换建议，确保内容合规且保留原意。",
    "author": "大鹏",
    "folder": "多平台风险词检查",
    "zip": "resources/skill-kit/packs/099-多平台风险词检查.zip",
    "page": "resources/skill-kit/index.html#poju-099"
  },
  {
    "n": 100,
    "id": "poju-100",
    "name": "自然文风改写",
    "cat": "写作",
    "brief": "自然文风改写工具，专门针对公众号、小红书、抖音口播、商务邮件等场景，将带有机器腔、公文腔或营销腔的文本改写得更加自然、真实。核心功能包括：智能判断发布平台以调整改写强度；提供轻修、标准、重写等多种处理模式；严格保护事实、数字、名称及作者原意，杜绝虚构；内置模板腔诊断机制，识别并消除宏大开头、空泛升华等常见问题；支持长文…",
    "author": "大鹏",
    "folder": "自然文风改写",
    "zip": "resources/skill-kit/packs/100-自然文风改写.zip",
    "page": "resources/skill-kit/index.html#poju-100"
  },
  {
    "n": 101,
    "id": "poju-101",
    "name": "公考报考顾问",
    "cat": "学习教育",
    "brief": "公考报考顾问是一款专注于解答国家公务员考试、省考、事业单位、选调生、军队文职等14类体制内招录问题的智能助手。它能根据用户的学历、专业、政治面貌等条件，结合官方公告口径，提供精准的报考资格判断、岗位选择建议及备考指导。通过标准化的判定模板和风险提示，帮助用户规避报考风险，明确下一步核验动作，是考生备考过程中的得力参谋。",
    "author": "大鹏",
    "folder": "公考报考顾问",
    "zip": "resources/skill-kit/packs/101-公考报考顾问.zip",
    "page": "resources/skill-kit/index.html#poju-101"
  },
  {
    "n": 102,
    "id": "poju-102",
    "name": "GitHub 热门AI项目趋势追踪",
    "cat": "数据分析",
    "brief": "GitHub 热门 AI 项目趋势追踪工具。自动从 GitHub 公开接口搜索人工智能相关仓库，生成包含榜单、赛道观察和风险数据的趋势报告。支持按时间范围（周/月）和特定方向（如 Agent、RAG、LLM）筛选。脚本具备严格的数据完整性校验，对缺失字段明确标注，并在取数失败时输出模板而非虚假结论，确保报告的可复查性和…",
    "author": "大鹏",
    "folder": "GitHub 热门AI项目趋势追踪",
    "zip": "resources/skill-kit/packs/102-GitHub-热门AI项目趋势追踪.zip",
    "page": "resources/skill-kit/index.html#poju-102"
  },
  {
    "n": 103,
    "id": "poju-103",
    "name": "校招岗位搜索",
    "cat": "研究检索",
    "brief": "按企业、岗位、城市、届别或秋招/春招关键词查找校园招聘岗位，整理可投递岗位清单。结果按更新时间倒序排列，保留校招名称、公司、岗位方向、工作地点、截止时间、投递入口、来源可信度和下一步投递建议。内置届别窗口校验机制，自动识别过期招聘并推荐当前开放届别，确保信息时效性。",
    "author": "大鹏",
    "folder": "校招岗位搜索",
    "zip": "resources/skill-kit/packs/103-校招岗位搜索.zip",
    "page": "resources/skill-kit/index.html#poju-103"
  },
  {
    "n": 104,
    "id": "poju-104",
    "name": "技术 SEO 检测工具",
    "cat": "开发运维",
    "brief": "一款面向网站上线前后的 SEO/GEO/AEO 综合复核工具。提供页面矩阵对账、Indexability 检查、SERP 竞争力分析、技术 SEO 审计（Robots/Sitemap/Canonical/Schema）、GSC/IndexNow 提交验证以及 AI 可引用结构（llms.txt）配置指南。内置 Pyth…",
    "author": "俊哥AI",
    "folder": "技术 SEO 检测工具",
    "zip": "resources/skill-kit/packs/104-技术-SEO-检测工具.zip",
    "page": "resources/skill-kit/index.html#poju-104"
  },
  {
    "n": 105,
    "id": "poju-105",
    "name": "独立站合规检测",
    "cat": "工具",
    "brief": "独立站合规检测 Skill，帮助开发者将站点的数据收集、AI API、支付、Cookie 及素材风险转化为可上线的 Privacy Policy、Terms of Service、Cookie 声明和 Refund 政策草稿。内置合规风险矩阵、Cloudflare 静态站法律页验证指南（含邮箱混淆处理）及自动化校验脚本…",
    "author": "俊哥AI",
    "folder": "独立站合规检测",
    "zip": "resources/skill-kit/packs/105-独立站合规检测.zip",
    "page": "resources/skill-kit/index.html#poju-105"
  },
  {
    "n": 106,
    "id": "poju-106",
    "name": "冷启动增长与UTM",
    "cat": "自动化",
    "brief": "这是一个面向网站发布后冷启动阶段的自动化辅助工具。它指导用户执行目录提交、社区发布和周刊投稿等增长策略，并提供标准化的交付物模板（如 Launch Asset Pack）和 UTM 链接生成脚本。通过内置的输入契约和质量闸门检查，确保在 QA/SEO/合规通过后进行推广，同时记录关键数据以便后续复盘。适用于需要系统化执…",
    "author": "俊哥AI",
    "folder": "冷启动增长与UTM",
    "zip": "resources/skill-kit/packs/106-冷启动增长与UTM.zip",
    "page": "resources/skill-kit/index.html#poju-106"
  },
  {
    "n": 107,
    "id": "poju-107",
    "name": "小红书笔记工作台",
    "cat": "写作",
    "brief": "小红书笔记工作台，适合把一个想法、产品、经历、课程、文章或素材做成小红书图文笔记，包括标题、封面文字、正文、轮播结构、结尾互动和发布前检查。",
    "author": "小林",
    "folder": "小红书笔记工作台",
    "zip": "resources/skill-kit/packs/107-小红书笔记工作台.zip",
    "page": "resources/skill-kit/index.html#poju-107"
  },
  {
    "n": 108,
    "id": "poju-108",
    "name": "新手教程写作助手",
    "cat": "写作",
    "brief": "一款专注于新手友好型知识教程生成的 AI 助手。它能将工具使用、操作方法、课程案例及技术流程转化为结构清晰的实操手册、公众号文章或小红书笔记。内置标准化写作模板，强调以真实项目贯穿始终，确保每一步都有明确动作、原因解释及排错指南。支持多平台风格适配（如公众号的深度解析、小红书的清单式避坑、课程讲稿的口语互动），并强制要…",
    "author": "小林",
    "folder": "新手教程写作助手",
    "zip": "resources/skill-kit/packs/108-新手教程写作助手.zip",
    "page": "resources/skill-kit/index.html#poju-108"
  },
  {
    "n": 109,
    "id": "poju-109",
    "name": "问卷统计与需求洞察",
    "cat": "数据分析",
    "brief": "一款专业的问卷结果分析工具，适用于课程反馈、社群调研、用户满意度及 NPS 等场景。它不仅能自动处理单选题、多选题、评分题和开放题，还能进行交叉分析和优先级判断。通过内置的 Python 脚本快速生成统计报告，并结合 AI 提供深度的业务解释和改进建议，帮助团队从数据中提炼 actionable insights。",
    "author": "小林",
    "folder": "问卷统计与需求洞察",
    "zip": "resources/skill-kit/packs/109-问卷统计与需求洞察.zip",
    "page": "resources/skill-kit/index.html#poju-109"
  },
  {
    "n": 110,
    "id": "poju-110",
    "name": "流程与规范编写助手",
    "cat": "工具",
    "brief": "SOP 和工作流程编写助手。帮助用户将重复性工作、运营流程、课程交付、客服处理、内容发布、数据处理或团队协作沉淀为标准化的执行手册。支持按风险等级确定颗粒度，明确角色分工、输入输出、检查点及异常升级规则，提供可勾选的检查清单和记录模板，旨在降低沟通成本与出错率，提升执行效率。",
    "author": "小林",
    "folder": "流程与规范编写助手",
    "zip": "resources/skill-kit/packs/110-流程与规范编写助手.zip",
    "page": "resources/skill-kit/index.html#poju-110"
  },
  {
    "n": 111,
    "id": "poju-111",
    "name": "一人公司内容策略",
    "cat": "自动化",
    "brief": "专为一人公司设计的内容策略生成助手。根据产品、服务、销售数据、客户问题及时间预算，智能判断内容的推、稳、调、停策略。内置内容漏斗模型与30天排期模板，帮助个人创业者制定低耗时、高转化的内容计划，避免盲目选题，聚焦获客与成交。",
    "author": "小林",
    "folder": "一人公司内容策略",
    "zip": "resources/skill-kit/packs/111-一人公司内容策略.zip",
    "page": "resources/skill-kit/index.html#poju-111"
  },
  {
    "n": 112,
    "id": "poju-112",
    "name": "短视频脚本工作台",
    "cat": "写作",
    "brief": "短视频脚本工作台，专为抖音、视频号、快手、B站等竖屏平台设计。它能将观点、故事、产品说明或课程素材转化为可拍摄的完整脚本包。核心功能包括：基于留存率优化的四段式结构（钩子、确认、兑现、CTA）；自动生成逐秒分镜表，涵盖口播台词、屏幕文字、画面描述及素材关键词；提供多平台规格参数建议；内置 AI 合成内容声明及医疗/金融…",
    "author": "小林",
    "folder": "短视频脚本工作台",
    "zip": "resources/skill-kit/packs/112-短视频脚本工作台.zip",
    "page": "resources/skill-kit/index.html#poju-112"
  },
  {
    "n": 113,
    "id": "poju-113",
    "name": "个人口吻档案",
    "cat": "写作",
    "brief": "个人口吻档案生成工具。从用户的文章、朋友圈、社群发言等材料中提取真实的表达风格、句式习惯和禁用词库。支持多平台语域区分（如小红书、公众号、朋友圈），提供置信度评估以确保结论可靠性。输出包含可复用的写作提示词和风格质检清单，帮助创作者在后续内容生产中保持“像本人”的自然语气，避免 AI 味过重。",
    "author": "小林",
    "folder": "个人口吻档案",
    "zip": "resources/skill-kit/packs/113-个人口吻档案.zip",
    "page": "resources/skill-kit/index.html#poju-113"
  },
  {
    "n": 114,
    "id": "poju-114",
    "name": "会议纪要整理助手",
    "cat": "工具",
    "brief": "这是一个专业的会议纪要整理工具，旨在将杂乱的会议材料（如逐字稿、聊天记录、直播复盘、访谈记录）转化为清晰、结构化的文档。它不仅能提取核心结论和议题，还能精准识别决议、待办事项（包含责任人、截止时间）、分歧点及遗留问题。Skill 内置了针对不同类型会议（如周会、项目会、客户会）的处理策略，强调不编造信息、准确区分已决与…",
    "author": "小林",
    "folder": "会议纪要整理助手",
    "zip": "resources/skill-kit/packs/114-会议纪要整理助手.zip",
    "page": "resources/skill-kit/index.html#poju-114"
  },
  {
    "n": 115,
    "id": "poju-115",
    "name": "长内容多平台改编",
    "cat": "写作",
    "brief": "本Skill旨在协助用户将公众号文章、直播转写、课程稿等长内容素材，拆解为适合小红书、抖音、视频号、朋友圈等多平台的独立传播内容包。通过提取观点、故事、步骤等内容原子，按平台特性重写标题、正文及脚本，并提供分发节奏建议与风险检查，确保内容原创性且符合各平台规范。",
    "author": "小林",
    "folder": "长内容多平台改编",
    "zip": "resources/skill-kit/packs/115-长内容多平台改编.zip",
    "page": "resources/skill-kit/index.html#poju-115"
  },
  {
    "n": 116,
    "id": "poju-116",
    "name": "正式报告写作助手",
    "cat": "写作",
    "brief": "正式报告和方案成文。适合把零散素材、调研记录、数据结论、会议要点、项目复盘或口述内容整理成结构清楚、语气正式、可提交的调研报告、方案书、复盘报告、工作总结和立项材料。提供从素材分类、读者分析到最终排版输出的完整工作流，并附带 Markdown 转 A4 HTML/PDF 的实用脚本。",
    "author": "小林",
    "folder": "正式报告写作助手",
    "zip": "resources/skill-kit/packs/116-正式报告写作助手.zip",
    "page": "resources/skill-kit/index.html#poju-116"
  },
  {
    "n": 117,
    "id": "poju-117",
    "name": "表格公式助手",
    "cat": "工具",
    "brief": "Excel 和 WPS 公式助手。适合把自然语言需求转成可粘贴公式，解释已有公式，排查 #N/A、#REF!、#VALUE!，处理条件统计、跨表匹配、日期计算、文本提取和常见兼容问题。",
    "author": "小林",
    "folder": "表格公式助手",
    "zip": "resources/skill-kit/packs/117-表格公式助手.zip",
    "page": "resources/skill-kit/index.html#poju-117"
  },
  {
    "n": 118,
    "id": "poju-118",
    "name": "表格数据清洗",
    "cat": "数据分析",
    "brief": "一款专注于表格和 CSV 数据清洗的自动化 Skill。它能自动处理重复行、空值、日期格式混乱、金额符号及文本空格等问题，并输出清洗后的文件和详细的清洗日志。通过字段体检和异常值标记机制，确保数据安全且业务口径准确，适合需要整理原始数据进行后续分析的场景。",
    "author": "小林",
    "folder": "表格数据清洗",
    "zip": "resources/skill-kit/packs/118-表格数据清洗.zip",
    "page": "resources/skill-kit/index.html#poju-118"
  },
  {
    "n": 119,
    "id": "poju-119",
    "name": "客户跟进助手",
    "cat": "工具",
    "brief": "专为一人公司设计的客户跟进与线索分诊助手。能够整理私信咨询、表单线索、成交记录及售后问题，自动输出优先级判断、依据、下一步动作及标准化短话术。内置脱敏机制，严格禁止替用户发送消息或承诺结果，确保合规高效地管理客户关系。",
    "author": "小林",
    "folder": "客户跟进助手",
    "zip": "resources/skill-kit/packs/119-客户跟进助手.zip",
    "page": "resources/skill-kit/index.html#poju-119"
  },
  {
    "n": 120,
    "id": "poju-120",
    "name": "内容发布前检查",
    "cat": "写作",
    "brief": "这是一个专注于内容发布前质检的 Skill，旨在帮助用户判断小红书、短视频脚本、公众号文章等内容的清晰度、可信度、合规性及平台适配度。它不代写内容，而是通过严格的审核流程输出发布结论（SHIP/FIX/BLOCK/UNDECIDED），定位具体问题并提供局部修改建议。内置分平台检查表（如小红书、抖音、公众号等）和高风险…",
    "author": "小林",
    "folder": "内容发布前检查",
    "zip": "resources/skill-kit/packs/120-内容发布前检查.zip",
    "page": "resources/skill-kit/index.html#poju-120"
  },
  {
    "n": 121,
    "id": "poju-121",
    "name": "内容日历排期",
    "cat": "自动化",
    "brief": "内容日历排期工具。适合把账号、社群、课程、企业号或个人内容计划排成周/月日历，按产能、栏目、平台、主题、素材状态和复盘节奏安排可执行更新计划。支持输入配置 JSON，自动生成带真实日期的周/月排期表（Markdown + CSV），含热点弹性位与库存提醒。CSV 可导入飞书、Notion 或表格继续跟踪状态。",
    "author": "小林",
    "folder": "内容日历排期",
    "zip": "resources/skill-kit/packs/121-内容日历排期.zip",
    "page": "resources/skill-kit/index.html#poju-121"
  },
  {
    "n": 122,
    "id": "poju-122",
    "name": "社群发帖与答疑助手",
    "cat": "写作",
    "brief": "社群发帖、答疑和互动分诊。适合微信群、飞书群、知识星球、训练营、私域社群的通知、活动预告、作业提醒、答疑回复、投诉安抚、复盘总结、转化说明和评论私信批量回复。",
    "author": "小林",
    "folder": "社群发帖与答疑助手",
    "zip": "resources/skill-kit/packs/122-社群发帖与答疑助手.zip",
    "page": "resources/skill-kit/index.html#poju-122"
  },
  {
    "n": 123,
    "id": "poju-123",
    "name": "数据图表可视化",
    "cat": "数据分析",
    "brief": "这是一个专注于数据可视化建议与生成的工具。它能帮助用户分析 CSV 或表格数据，根据数据特征（如比较大小、看趋势、看占比等）推荐最合适的图表类型（柱状图、折线图、饼图、散点图等）。Skill 内置 Python 脚本，可自动处理数据聚合、TopN 筛选，并直接生成零依赖的 SVG 矢量图表文件。同时提供详细的图表设计原…",
    "author": "小林",
    "folder": "数据图表可视化",
    "zip": "resources/skill-kit/packs/123-数据图表可视化.zip",
    "page": "resources/skill-kit/index.html#poju-123"
  },
  {
    "n": 124,
    "id": "poju-124",
    "name": "经营周报与风险提醒",
    "cat": "工具",
    "brief": "一款专为一人公司或小团队设计的自动化经营简报工具。它能将零散的收入、回款、客户线索、项目进度、内容表现及交付状态等流水信息，智能归类并转化为结构化的周报、月报、经营快照或现金提醒。Skill 强调基于事实而非估算，自动识别业务风险与卡点，并提炼出唯一的优先处理事项及下期行动清单，帮助管理者清晰掌握经营状况，提升决策效率…",
    "author": "小林",
    "folder": "经营周报与风险提醒",
    "zip": "resources/skill-kit/packs/124-经营周报与风险提醒.zip",
    "page": "resources/skill-kit/index.html#poju-124"
  },
  {
    "n": 125,
    "id": "poju-125",
    "name": "账号定位与栏目规划",
    "cat": "写作",
    "brief": "一款专业的账号定位与栏目规划助手。它不包装虚假人设，而是基于用户的真实经历、目标用户和业务目标，深入诊断账号定位。功能包括：1. 定位问诊：引导用户明确身份、受众、信任来源及转化路径；2. 骨架输出：生成具体的账号定位句和内容支柱（获客、专业、信任、关系、转化）；3. 栏目设计：根据平台特性（如小红书、抖音、公众号）定…",
    "author": "小林",
    "folder": "账号定位与栏目规划",
    "zip": "resources/skill-kit/packs/125-账号定位与栏目规划.zip",
    "page": "resources/skill-kit/index.html#poju-125"
  },
  {
    "n": 126,
    "id": "poju-126",
    "name": "AI 产品定价校准",
    "cat": "工具",
    "brief": "AI 产品定价校准工具，协助设计 Free/Pro/Lifetime 等套餐，通过竞品锚点、成本模型及转化路径分析，确保定价不亏损且合规。内置报告校验脚本，提供标准化交付模板与交接格式，适用于 SaaS 及 AI 生成类产品的商业化阶段。",
    "author": "俊哥AI",
    "folder": "AI 产品定价校准",
    "zip": "resources/skill-kit/packs/126-AI-产品定价校准.zip",
    "page": "resources/skill-kit/index.html#poju-126"
  },
  {
    "n": 127,
    "id": "poju-127",
    "name": "剪映/CapCut 自动剪辑助手",
    "cat": "音视频",
    "brief": "剪映/CapCut 自动剪辑助手是一款专为 macOS 平台设计的自动化辅助工具。它利用 Computer Use 技术模拟人工操作，帮助用户高效完成剪映专业版的各项任务。主要功能包括：智能导入视频/音频素材并放入时间线、执行画面裁切缩放、调整字幕标题、添加音效贴纸以及最终导出视频。该 Skill 明确了与第三方 AS…",
    "author": "俊哥AI",
    "folder": "剪映_CapCut 自动剪辑助手",
    "zip": "resources/skill-kit/packs/127-剪映_CapCut-自动剪辑助手.zip",
    "page": "resources/skill-kit/index.html#poju-127"
  },
  {
    "n": 128,
    "id": "poju-128",
    "name": "AI 热点资讯查询与简报生成",
    "cat": "研究检索",
    "brief": "这是一个 AI 热点资讯查询与简报生成工具。它通过可配置的 REST API（如 `AI_NEWS_API_BASE`）获取今日热点、日报及归档数据，并根据用户意图（如“今天发生了什么”、“模型发布”等）智能路由查询。Skill 会将原始数据整理为结构化的中文 Markdown 简报，包含标题、摘要和原文链接，同时严格…",
    "author": "俊哥AI",
    "folder": "AI 热点资讯查询与简报生成",
    "zip": "resources/skill-kit/packs/128-AI-热点资讯查询与简报生成.zip",
    "page": "resources/skill-kit/index.html#poju-128"
  },
  {
    "n": 129,
    "id": "poju-129",
    "name": "Image2 商业设计提示词大师",
    "cat": "设计",
    "brief": "Image2 商业设计提示词大师是一款专为 ChatGPT Images 2.0 (gpt-image-2) 设计的辅助工具。它能将用户的一句话或简单想法，扩写并润色为可直接使用的高质量商业设计图提示词。适用范围包括室内空间、建筑、展陈、零售、产品、包装、品牌视觉、海报、电商和商业摄影等场景，同时也支持基于参考图的改图…",
    "author": "黄桃子",
    "folder": "Image2 商业设计提示词大师",
    "zip": "resources/skill-kit/packs/129-Image2-商业设计提示词大师.zip",
    "page": "resources/skill-kit/index.html#poju-129"
  },
  {
    "n": 130,
    "id": "poju-130",
    "name": "AI工具测评",
    "cat": "写作",
    "brief": "本技能专为职场人和创作者设计，用于将网站或工具转化为高完播率的30秒短视频口播文案。它扮演「工具测评博主」角色，严格遵循“总介绍-分介绍-递进-举例-价值递进-收尾”六步框架，确保文案节奏强、有网感且字数控制在220字以内。同时提供爆款标题、封面建议、四维标签及争议弹幕等全套运营封装物料，助力在小红书和抖音平台提升内容…",
    "author": "黄桃子",
    "folder": "AI工具测评",
    "zip": "resources/skill-kit/packs/130-AI工具测评.zip",
    "page": "resources/skill-kit/index.html#poju-130"
  },
  {
    "n": 131,
    "id": "poju-131",
    "name": "拉片助手",
    "cat": "音视频",
    "brief": "专业视频拉片与镜头分析助手：自动检测真实切镜，提取代表帧、分析帧、音频信号与OCR，并以59字段专业模型输出摄影语言、叙事营销、AI视频提示词和飞书Base幂等数据。",
    "author": "非叔Levie",
    "folder": "拉片助手",
    "zip": "resources/skill-kit/packs/131-拉片助手.zip",
    "page": "resources/skill-kit/index.html#poju-131"
  },
  {
    "n": 132,
    "id": "poju-132",
    "name": "从 PRD 生成高转化落地页文案",
    "cat": "写作",
    "brief": "这是一个专注于落地页文案生成与转化的 Skill。它能帮助用户把产品需求文档（PRD）、定价策略、合规要求和 SEO 指标转化为可直接设计、上线的高转化率页面文案。Skill 提供了标准化的阶段流程，包括消息层级构建、转化结构设计、SEO 冻结检查以及合规扫描。内置了验收清单和质量门槛，确保文案简洁、结果导向且无空泛 …",
    "author": "俊哥AI",
    "folder": "从 PRD 生成高转化落地页文案",
    "zip": "resources/skill-kit/packs/132-从-PRD-生成高转化落地页文案.zip",
    "page": "resources/skill-kit/index.html#poju-132"
  },
  {
    "n": 133,
    "id": "poju-133",
    "name": "把当前对话沉淀为结构化 Markdown/Obsidian 笔记",
    "cat": "工具",
    "brief": "此 Skill 可将当前对话的精华内容自动提取、结构化，并保存到 Obsidian 指定文件夹中。它智能过滤无关对话和调试输出，保留问题解决方案、代码片段、决策原因及关键要点。支持自定义路径和文件名规则，确保笔记独立可读且格式规范，无需额外连接即可通过 Bash 工具直接写入文件，提升知识沉淀效率。",
    "author": "俊哥AI",
    "folder": "把当前对话沉淀为结构化 Markdown_Obsidian 笔记",
    "zip": "resources/skill-kit/packs/133-把当前对话沉淀为结构化-Markdown_Obsidian-笔记.zip",
    "page": "resources/skill-kit/index.html#poju-133"
  },
  {
    "n": 134,
    "id": "poju-134",
    "name": "网站上线前 GO/NO-GO 验收与分级",
    "cat": "开发运维",
    "brief": "这是一个面向网站发布前的 QA 验收 Skill。它通过真实用户任务执行最终验收，依据 PM/SEO/合规等闸门进行准入检查，并覆盖 5 秒测试、技术 Smoke 测试及权限数据验证。Skill 定义了严格的输入契约（如账号、Token 准备）和安全话术，确保在缺乏关键权限时阻断流程而非盲目执行。输出包括 GO/NO-…",
    "author": "俊哥AI",
    "folder": "网站上线前 GO_NO-GO 验收与分级",
    "zip": "resources/skill-kit/packs/134-网站上线前-GO_NO-GO-验收与分级.zip",
    "page": "resources/skill-kit/index.html#poju-134"
  },
  {
    "n": 135,
    "id": "poju-135",
    "name": "技能安全安装助手",
    "cat": "开发运维",
    "brief": "安全地审计和安装来自 GitHub、npx 或市场链接等外部来源的 Agent Skills。该 Skill 强制执行“验证-审计-安装”工作流，避免盲目执行远程代码。它首先检查本地是否已存在该技能，验证仓库 URL 的有效性，然后将代码克隆到临时目录进行扫描。通过内置的 Python 扫描器检测高危模式（如反向 sh…",
    "author": "宛月",
    "folder": "技能安全安装助手",
    "zip": "resources/skill-kit/packs/135-技能安全安装助手.zip",
    "page": "resources/skill-kit/index.html#poju-135"
  },
  {
    "n": 136,
    "id": "poju-136",
    "name": "adsense 过审检测",
    "cat": "开发运维",
    "brief": "AdSense 网站准备度审计工具。基于 Google AdSense 官方政策，对网站进行全面的合规性检查。涵盖资格验证、站点所有权、内容质量、导航与用户体验、爬虫可访问性、广告程序政策、发布者政策及隐私数据要求等维度。提供逐项检查表（Pass/Fail/Unknown/N/A），识别阻碍审批的 Blocker 和高…",
    "author": "俊哥AI",
    "folder": "adsense 过审检测",
    "zip": "resources/skill-kit/packs/136-adsense-过审检测.zip",
    "page": "resources/skill-kit/index.html#poju-136"
  },
  {
    "n": 137,
    "id": "poju-137",
    "name": "公众号写作",
    "cat": "写作",
    "brief": "这是一个专注于微信公众号实战文章写作的自动化工作流。它能够将新闻链接、产品资料、实践记录、采访录音或零散观点转化为结构严谨、风格自然且适合微信阅读习惯的长文或短图文。核心功能包括：智能判断文章类型（如实践复盘、行业解读），建立严格的事实账本以杜绝编造数据，提炼文章主线，生成多种风格的标题候选，设计高吸引力的开头，以及编…",
    "author": "俊哥AI",
    "folder": "公众号写作",
    "zip": "resources/skill-kit/packs/137-公众号写作.zip",
    "page": "resources/skill-kit/index.html#poju-137"
  },
  {
    "n": 138,
    "id": "poju-138",
    "name": "前端审美提升",
    "cat": "设计",
    "brief": "在生成或审查网页、前端组件及 HTML/CSS 页面时提供专业审美决策。本技能专注于规避平庸的 AI 设计风格，从排版、色彩、动效、布局、背景五个核心维度出发，打造具有独特个性和记忆点的前端界面。通过明确的触发场景和详细的执行流程，帮助用户打破常规网格与模板化配色，实现更具张力和高级感的视觉呈现。适用于落地页、个人主页…",
    "author": "一只阿木木",
    "folder": "前端审美提升",
    "zip": "resources/skill-kit/packs/138-前端审美提升.zip",
    "page": "resources/skill-kit/index.html#poju-138"
  },
  {
    "n": 139,
    "id": "poju-139",
    "name": "文章手绘配图",
    "cat": "设计",
    "brief": "这是一个专注于生成阿超风格（怪诞、手绘、留白）中文正文配图的自动化技能。它支持圆仔、小白和线条人三种视觉 IP，提供从核心观点提炼、配图策略制定到单张图像生成的完整工作流。内置严格的 QA 检查清单和风格 DNA 规范，确保输出图片保持简洁清爽、天马行空的视觉风格，避免 PPT 感或可爱卡通化，适用于博客、Notion…",
    "author": "老张",
    "folder": "文章手绘配图",
    "zip": "resources/skill-kit/packs/139-文章手绘配图.zip",
    "page": "resources/skill-kit/index.html#poju-139"
  },
  {
    "n": 140,
    "id": "poju-140",
    "name": "微信公众号文章转 PDF",
    "cat": "工具",
    "brief": "本 Skill 可将微信公众号文章（mp.weixin.qq.com 链接）读取并转换为排版整洁的 PDF 文件。当用户粘贴公众号文章链接、要求把这篇公众号文章存成 PDF / 导出 PDF / 转成 PDF、或需要对公众号文章做离线留存时使用本 skill。自动提取标题、作者、发布时间和正文，修复微信懒加载图片并保留…",
    "author": "宛月",
    "folder": "微信公众号文章转 PDF",
    "zip": "resources/skill-kit/packs/140-微信公众号文章转-PDF.zip",
    "page": "resources/skill-kit/index.html#poju-140"
  },
  {
    "n": 141,
    "id": "poju-141",
    "name": "公众号文章爬取与润色",
    "cat": "写作",
    "brief": "一款自动化文章处理工具，能够从指定 URL 抓取网页内容，利用大语言模型对正文进行专业润色优化，并智能提取关键词与标签。支持自定义关键词数量、标签数量及目标语言，提供结构化输出格式，适用于 SEO 优化、内容二次加工及素材整理场景。",
    "author": "老张",
    "folder": "公众号文章爬取与润色",
    "zip": "resources/skill-kit/packs/141-公众号文章爬取与润色.zip",
    "page": "resources/skill-kit/index.html#poju-141"
  },
  {
    "n": 142,
    "id": "poju-142",
    "name": "公众号爆文精细拆解",
    "cat": "写作",
    "brief": "一款针对微信公众号爆款文章的纳米像素级拆解工具。它提供从战略定位到微观标点的十步拆解流程，核心能力在于对框架结构、内容风格、语言口吻三个维度进行显微镜级放大分析。输出包括综合总结、可照做的爆款要素模仿清单以及个性化的科学学习建议，帮助用户深入理解爆文机制并实现有效模仿。",
    "author": "宛月",
    "folder": "公众号爆文精细拆解",
    "zip": "resources/skill-kit/packs/142-公众号爆文精细拆解.zip",
    "page": "resources/skill-kit/index.html#poju-142"
  },
  {
    "n": 143,
    "id": "poju-143",
    "name": "AI 短视频自动生产线",
    "cat": "音视频",
    "brief": "AI短视频自动生产线。通过一句话指令触发，自动完成文案撰写、声音克隆旁白生成、AI场景素材生成（赛博科技风）、Remotion渲染及ffmpeg音频合成，最终输出竖屏MP4成品。支持Telegram原生附件交付，内置完善的错误排查与兜底策略。使用前需配置FAL_KEY等环境变量。",
    "author": "俊哥AI",
    "folder": "AI 短视频自动生产线",
    "zip": "resources/skill-kit/packs/143-AI-短视频自动生产线.zip",
    "page": "resources/skill-kit/index.html#poju-143"
  },
  {
    "n": 144,
    "id": "poju-144",
    "name": "文章发布前质量审核",
    "cat": "写作",
    "brief": "文章发布前质量审核 Skill，用于检查事实依据、内容质量、AI 味、平台适配、版权与发布风险、素材完整性，并给出可发布、修改后发布或人工确认建议。适用于公众号、小红书、知乎、今日头条、博客及其他公开内容发布前复核。",
    "author": "菜叶",
    "folder": "文章发布前质量审核",
    "zip": "resources/skill-kit/packs/144-文章发布前质量审核.zip",
    "page": "resources/skill-kit/index.html#poju-144"
  },
  {
    "n": 145,
    "id": "poju-145",
    "name": "李继刚大佬的 Skill 合集",
    "cat": "学习教育",
    "brief": "李继刚大佬的 Skill 合集：收录 20 个面向深度思考、阅读、写作与知识表达的用户型 Skill。覆盖拆书、论文阅读、伴读、概念解剖、盲区扫描、约束/降秩/本质/结构分析、白话改写、问答提炼、写作、古文精读、内容卡片、演讲、投资、关系与圆桌讨论。开源仓库：https://github.com/lijigang/lj…",
    "author": "左同学",
    "folder": "李继刚大佬的 Skill 合集",
    "zip": "resources/skill-kit/packs/145-李继刚大佬的-Skill-合集.zip",
    "page": "resources/skill-kit/index.html#poju-145"
  },
  {
    "n": 146,
    "id": "poju-146",
    "name": "edge浏览器控制",
    "cat": "自动化",
    "brief": "在 Windows 上通过 CDP (Chrome DevTools Protocol) 自动化操控本机 Microsoft Edge 浏览器。核心优势在于优先连接并复用用户正在运行的 Edge 实例，保留现有的登录状态、Cookie 和标签页，避免创建隔离的无痕环境。支持自动探测 CDP 端口、智能启动/重启浏览器以…",
    "author": "小机AI智能体",
    "folder": "edge浏览器控制",
    "zip": "resources/skill-kit/packs/146-edge浏览器控制.zip",
    "page": "resources/skill-kit/index.html#poju-146"
  },
  {
    "n": 147,
    "id": "poju-147",
    "name": "DeepSeek Harness 启动器",
    "cat": "开发运维",
    "brief": "DeepSeek Harness 启动器：自动化管理本地 deepseek-harness Web 服务。支持检测服务状态、后台启动、验证就绪及停止进程。适用于需要快速启动、重启或监控位于 D:\\githubProjects\\deepseek-harness 项目的用户，自动处理端口冲突与依赖安装问题，提供稳定的本地开…",
    "author": "雪见RPA+AI",
    "folder": "DeepSeek Harness 启动器",
    "zip": "resources/skill-kit/packs/147-DeepSeek-Harness-启动器.zip",
    "page": "resources/skill-kit/index.html#poju-147"
  },
  {
    "n": 148,
    "id": "poju-148",
    "name": "小红书 Skill 排行榜查询器",
    "cat": "数据分析",
    "brief": "小红书 Skill 排行榜查询器。此工具通过内置的本地客户端查询小红书 REDSkill 的排行榜数据，包括热门技能、累计用户数、累计使用次数、7日增长、每日新技能及作者发布排名等。支持关键词搜索、技能详情查看及数据导出（CSV/JSON）。无需额外配置，自动处理本地缓存以优化访问效率。适用于需要获取和分析小红书平台技…",
    "author": "雪见RPA+AI",
    "folder": "小红书 Skill 排行榜查询器",
    "zip": "resources/skill-kit/packs/148-小红书-Skill-排行榜查询器.zip",
    "page": "resources/skill-kit/index.html#poju-148"
  },
  {
    "n": 149,
    "id": "poju-149",
    "name": "工业软件变更影响审查",
    "cat": "开发运维",
    "brief": "面向工业设备软件的高级变更影响审查工程师。在修改 Qt/C++、Python 等工业上位机、HMI、PLC/HMI 集成及运动控制代码前，分析变更对模块、线程、状态机、设备通信、共享变量、持久化数据及安全联锁的影响，降低回归故障风险。提供标准化的影响分析流程、高风险变更模式识别、风险等级评估（R0-R3）以及自动化引用…",
    "author": "菜叶",
    "folder": "工业软件变更影响审查",
    "zip": "resources/skill-kit/packs/149-工业软件变更影响审查.zip",
    "page": "resources/skill-kit/index.html#poju-149"
  },
  {
    "n": 150,
    "id": "poju-150",
    "name": "Markdown 图片上云助手",
    "cat": "工具",
    "brief": "使用用户已配置的 PicGo-Core 上传本地图片，验证公开 HTTPS 地址，并生成或替换 Markdown 和 Obsidian 图片链接。适用于将本地截图、附件转换为可移植网络链接。Skill 严格复用现有配置，不保存密钥，支持只读检查、Dry-run 预演及敏感信息过滤，确保上传安全可控。",
    "author": "左同学",
    "folder": "Markdown 图片上云助手",
    "zip": "resources/skill-kit/packs/150-Markdown-图片上云助手.zip",
    "page": "resources/skill-kit/index.html#poju-150"
  },
  {
    "n": 151,
    "id": "poju-151",
    "name": "社媒互动机会雷达",
    "cat": "研究检索",
    "brief": "一款专注于社交媒体机会研究的辅助工具。它利用用户已登录的浏览器会话，在 X、Reddit、Product Hunt 等平台中扫描公开讨论，通过多维度的评分规则（传播潜力与回复价值）筛选高价值帖子。Skill 会生成包含证据、置信度及唯一回复草稿的报告，严格遵循只读原则，不自动发帖、刷量或绕过平台限制，旨在帮助用户高效发…",
    "author": "左同学",
    "folder": "社媒互动机会雷达",
    "zip": "resources/skill-kit/packs/151-社媒互动机会雷达.zip",
    "page": "resources/skill-kit/index.html#poju-151"
  },
  {
    "n": 152,
    "id": "poju-152",
    "name": "专业视频审片官",
    "cat": "音视频",
    "brief": "专业审查视频成片、粗剪、样片、广告片、宣传片、短视频、剧情片段、口播、课程视频或分镜脚本。从目标达成、叙事结构、节奏、画面、声音、字幕、品牌、技术交付、版权与合规层面发现问题，并输出带时间码、证据、优先级和修改目标的可执行审片意见。支持 GO/CONDITIONAL GO/NO-GO 结论判定，适用于成片验收、版本对比…",
    "author": "左同学",
    "folder": "专业视频审片官",
    "zip": "resources/skill-kit/packs/152-专业视频审片官.zip",
    "page": "resources/skill-kit/index.html#poju-152"
  },
  {
    "n": 153,
    "id": "poju-153",
    "name": "域名资产智能管家",
    "cat": "开发运维",
    "brief": "使用 Markdown 台账统一查询、记录和核对域名资产、注册商账号别名、到期时间、DNS 状态与交易流水。适用于新购、续费、转移、出售、退款、到期盘点和注册商后台只读核对；不把“记录域名”解释为授权购买、续费或修改 DNS。把 Markdown 作为事实真源，保持“域名主记录、注册商平台记录、交易流水”三类数据一致。…",
    "author": "左同学",
    "folder": "域名资产智能管家",
    "zip": "resources/skill-kit/packs/153-域名资产智能管家.zip",
    "page": "resources/skill-kit/index.html#poju-153"
  },
  {
    "n": 154,
    "id": "poju-154",
    "name": "Python 工业软件代码审查",
    "cat": "开发运维",
    "brief": "面向生产环境的高级 Python 代码审查工程师，重点审查工业软件、自动化软件、设备控制、数据采集、串口/网络通信和长期运行程序。核心目标是找出会造成程序崩溃、数据错误、设备命令丢失、状态误判、线程竞争、通信异常、资源泄漏、工艺时序错误或长期运行不稳定的真实问题。优先审查运行时正确性、并发安全、通信时序、恢复机制、资源…",
    "author": "菜叶",
    "folder": "Python 工业软件代码审查",
    "zip": "resources/skill-kit/packs/154-Python-工业软件代码审查.zip",
    "page": "resources/skill-kit/index.html#poju-154"
  },
  {
    "n": 155,
    "id": "poju-155",
    "name": "自由听·音频整理助手",
    "cat": "音视频",
    "brief": "在用户确认拥有保存权利时，从 YouTube 链接、Spotify 元数据链接或本地音频中提取、切分、命名和整理音频。支持章节识别、时间戳处理及人工轨道清单编辑。默认输出到 Music 目录，可指定格式（如 opus, m4a, mp3, flac）。严格禁止绕过 DRM、付费墙或登录保护，Spotify 链接仅用于获…",
    "author": "左同学",
    "folder": "自由听·音频整理助手",
    "zip": "resources/skill-kit/packs/155-自由听-音频整理助手.zip",
    "page": "resources/skill-kit/index.html#poju-155"
  },
  {
    "n": 156,
    "id": "poju-156",
    "name": "优质外链机会猎手",
    "cat": "工具",
    "brief": "本 Skill 旨在帮助用户发现并核验可自然获得的高质量外链机会。它支持读取目标网站、关键词及用户合法获取的外链导出数据（如 Ahrefs/Semrush 导出），通过内置脚本进行数据去重和风险预筛。核心功能包括：建立竞品样本、收集外链候选、核实具体来源页质量、将机会分类为保留/待复核/未核实/淘汰，并为高价值机会生成…",
    "author": "左同学",
    "folder": "优质外链机会猎手",
    "zip": "resources/skill-kit/packs/156-优质外链机会猎手.zip",
    "page": "resources/skill-kit/index.html#poju-156"
  },
  {
    "n": 157,
    "id": "poju-157",
    "name": "英语进阶陪练教练",
    "cat": "学习教育",
    "brief": "专为中文母语者设计的英语进阶教练 Skill。覆盖听、说、读、写、词汇、语法及职场场景（面试、会议、邮件）。核心功能包括制定个性化学习计划、模拟情景对话、提供精准写作反馈及阶段复盘。遵循“先输出后反馈”原则，注重实际应用能力而非单纯语法纠错。支持非正式水平评估，不替代官方考试认证，确保用户数据隐私与安全。",
    "author": "左同学",
    "folder": "英语进阶陪练教练",
    "zip": "resources/skill-kit/packs/157-英语进阶陪练教练.zip",
    "page": "resources/skill-kit/index.html#poju-157"
  },
  {
    "n": 158,
    "id": "poju-158",
    "name": "课件知识库转换助手",
    "cat": "工具",
    "brief": "将 PPT、PPTX 或 PDF 幻灯片整理成结构清晰、可搜索的 Markdown 知识文档。支持 PDF 文本层提取、OCR 识别、表格与流程重构，并在证据不足时标记待核对。适用于课程资料、培训课件和演讲幻灯片归档；不默认删除源文件，也不适用于需要保留原版视觉排版的逐像素转换。",
    "author": "左同学",
    "folder": "课件知识库转换助手",
    "zip": "resources/skill-kit/packs/158-课件知识库转换助手.zip",
    "page": "resources/skill-kit/index.html#poju-158"
  },
  {
    "n": 159,
    "id": "poju-159",
    "name": "微信视频号解析",
    "cat": "音视频",
    "brief": "解析微信视频号分享链接，获取作者、简介、封面、互动数据和短期有效的 H.264/H.265 媒体地址。支持预览、下载、转写、总结视频号内容。用户提供 https://weixin.qq.com/sph/ 链接，或要求预览、下载、查看详情、总结、转写、分析微信视频号视频内容时使用。默认只解析并返回元数据和媒体地址；只有用…",
    "author": "雪见RPA+AI",
    "folder": "微信视频号解析",
    "zip": "resources/skill-kit/packs/159-微信视频号解析.zip",
    "page": "resources/skill-kit/index.html#poju-159"
  },
  {
    "n": 160,
    "id": "poju-160",
    "name": "跨境专家军团 v01：6人专家团队（增长/供应链/商务/运营/创意/市场技术）",
    "cat": "工具",
    "brief": "跨境专家军团：由15年跨境操盘手「乔达成」主理的6人专家团队（增长/供应链/商务/运营/创意/市场技术），覆盖新品上线全链路、新市场进入、利润优化冲刺、老板快报四大场景，驱动6个月利润翻倍。当用户提到「上新品/新品全流程」「进入XX国/拓市场」「利润下降/降本增效/优化利润」「老板日报/今天怎么样/团队状态/目标进度」…",
    "author": "月亮姐姐数字康养🌙",
    "folder": "跨境专家军团 v01：6人专家团队（增长_供应链_商务_运营_创意_市场技术）",
    "zip": "resources/skill-kit/packs/160-跨境专家军团-v01-6人专家团队-增长_供应链_商务_运营_创意_市场技术.zip",
    "page": "resources/skill-kit/index.html#poju-160"
  },
  {
    "n": 161,
    "id": "poju-161",
    "name": "微信公众号文章搜索",
    "cat": "研究检索",
    "brief": "这是一个用于搜索微信公众号文章的自动化工具。它通过搜狗微信搜索接口 (weixin.sogou.com) 根据关键词查找文章列表，返回包含标题、摘要、发布时间、来源公众号及链接的 JSON 数据。支持指定返回数量（最多 50 条）、将结果保存为 JSON 文件，以及尝试将搜狗中间链接解析为真实的 mp.weixin.q…",
    "author": "雪见RPA+AI",
    "folder": "微信公众号文章搜索",
    "zip": "resources/skill-kit/packs/161-微信公众号文章搜索.zip",
    "page": "resources/skill-kit/index.html#poju-161"
  },
  {
    "n": 162,
    "id": "poju-162",
    "name": "小红书内容生成",
    "cat": "写作",
    "brief": "小红书笔记素材创作技能。当用户需要创建小红书笔记素材时使用这个技能。技能包含：根据用户的需求和提供的资料，撰写小红书笔记内容（标题+正文），生成图片卡片（封面+正文卡片）。",
    "author": "老张",
    "folder": "小红书内容生成",
    "zip": "resources/skill-kit/packs/162-小红书内容生成.zip",
    "page": "resources/skill-kit/index.html#poju-162"
  },
  {
    "n": 163,
    "id": "poju-163",
    "name": "手绘涂鸦漫画角色卡系统 V1.0",
    "cat": "设计",
    "brief": "这是一个手绘涂鸦漫画角色卡生成系统。它能将用户提供的「角色+动作+表情+名字」套入一套强制风格锁，输出可直接投喂给绘图模型（ImageGen）的中英双语完整提示词。生成的角色卡具有米白纸张质感、粗黑墨线、平涂上色及红蓝黑墨滴飞溅等独特视觉风格。支持图生图模式下的风格锁定与微调，确保输出一致的手绘涂鸦效果。",
    "author": "月亮姐姐数字康养🌙",
    "folder": "手绘涂鸦漫画角色卡系统 V1.0",
    "zip": "resources/skill-kit/packs/163-手绘涂鸦漫画角色卡系统-V1-0.zip",
    "page": "resources/skill-kit/index.html#poju-163"
  },
  {
    "n": 164,
    "id": "poju-164",
    "name": "精华文改稿专家",
    "cat": "写作",
    "brief": "这是一个专业的文章改稿与诊断工具，专门针对复盘、教程、方法论及经验分享等实用性内容。它通过循循善诱的方式，先肯定文章亮点，再犀利指出核心问题，并提供可落地的优化建议。Skill 内置了四步分析框架（优点分析、核心问题诊断、具体优化建议、最犀利改进建议），并依据特定的评价标准判断是否需要生成重写版本。若需重写，它将遵循标…",
    "author": "耳朵",
    "folder": "精华文改稿专家",
    "zip": "resources/skill-kit/packs/164-精华文改稿专家.zip",
    "page": "resources/skill-kit/index.html#poju-164"
  },
  {
    "n": 165,
    "id": "poju-165",
    "name": "小红书商品笔记文案生成",
    "cat": "写作",
    "brief": "这是一款专业的小红书爆款文案生成助手。它能够根据用户输入的标题，自动生成针对特定人群（如喜欢拍照、拍Vlog的女性）的图文笔记正文。文案遵循“痛点场景+解决方案+价值展示+行动指令”的核心公式，采用自然、大白话的风格，贴合年轻用户的审美。生成的内容注重SEO关键词植入和Emoji排版优化，字数控制在200字左右，旨在通…",
    "author": "飞锅✨",
    "folder": "小红书商品笔记文案生成",
    "zip": "resources/skill-kit/packs/165-小红书商品笔记文案生成.zip",
    "page": "resources/skill-kit/index.html#poju-165"
  },
  {
    "n": 166,
    "id": "poju-166",
    "name": "小红书爆款标题生成",
    "cat": "写作",
    "brief": "专业的小红书爆款标题生成助手。基于大疆相机用户及摄影博主场景，提供针对图文笔记的标题优化服务。内置七大爆款元素（成本、负面体验、人群定位、对比对立、反向操作、权威背书、场景化）及丰富的情绪词库，支持根据选题或关键词自动生成10个兼具吸引力与转化力的标题，助力提升笔记点击率。",
    "author": "飞锅✨",
    "folder": "小红书爆款标题生成",
    "zip": "resources/skill-kit/packs/166-小红书爆款标题生成.zip",
    "page": "resources/skill-kit/index.html#poju-166"
  },
  {
    "n": 167,
    "id": "poju-167",
    "name": "网页海报工坊",
    "cat": "设计",
    "brief": "网页海报工坊是一款能将自然语言描述转化为精美单文件 HTML 海报的 Skill。它利用大模型强大的代码生成能力，快速制作海报、长图、对比卡、结营卡等视觉内容。生成的 HTML 文件内置响应式设计和一键导出 PNG 按钮，解决了用户难以编写图像生成 Prompt 的痛点，且无需安装任何软件，直接在浏览器中即可预览和分享…",
    "author": "夏蝉",
    "folder": "网页海报工坊",
    "zip": "resources/skill-kit/packs/167-网页海报工坊.zip",
    "page": "resources/skill-kit/index.html#poju-167"
  },
  {
    "n": 168,
    "id": "poju-168",
    "name": "灵感编译器",
    "cat": "写作",
    "brief": "Glowcatch 是一款专为内容创作者设计的灵感编译器 Skill。它帮助你将日常捕捉的观点、数据、反例等灵感碎片，从原始记录转化为可检索、可调用的论证素材库。Skill 包含三大核心模块：捕捉层实现零摩擦记录，保持原文原貌；编译层对积累的记录进行结构化索引和议题关联；检索层则能在起草文章时，基于论点反向查找并匹配历…",
    "author": "成云杉",
    "folder": "灵感编译器",
    "zip": "resources/skill-kit/packs/168-灵感编译器.zip",
    "page": "resources/skill-kit/index.html#poju-168"
  },
  {
    "n": 169,
    "id": "poju-169",
    "name": "图片分析助手",
    "cat": "工具",
    "brief": "专为纯文本模型设计的图片分析技能。通过调用本地部署的 MiniMax-M3 识图接口，自动读取图片路径并转换为 Base64 格式发送给 API，返回详细的图片分析结果。支持传入自定义问题，内置 UTF-8 输出处理以解决乱码，并提供 JSON 输出和文件写入选项，适用于自动化办公、内容审核或数据提取等场景。",
    "author": "许沐xzx",
    "folder": "图片分析助手",
    "zip": "resources/skill-kit/packs/169-图片分析助手.zip",
    "page": "resources/skill-kit/index.html#poju-169"
  },
  {
    "n": 170,
    "id": "poju-170",
    "name": "南柯抖音图文发布工作流",
    "cat": "自动化",
    "brief": "南柯版抖音图文发布闭环工作流。通过 Windows 独立 Edge 和 CDP 准备并核验图片、标题与正文，严格选择抖音平台 BGM 与现有合集，执行发布前人工确认门禁，并在发布后回读标题、图片数量、状态、合集和配乐证据。当用户明确要求准备或发布抖音图文、给抖音图文选择 BGM 或合集、核验抖音图文发布结果时使用。仅处…",
    "author": "AI南柯",
    "folder": "南柯抖音图文发布工作流",
    "zip": "resources/skill-kit/packs/170-南柯抖音图文发布工作流.zip",
    "page": "resources/skill-kit/index.html#poju-170"
  },
  {
    "n": 171,
    "id": "poju-171",
    "name": "微信公众号漫画长图",
    "cat": "设计",
    "brief": "一个用于自动化生成原创中文微信公众号漫画长图的 Skill。支持主题引导、文案撰写、分镜设计、AI 生图（兼容 Codex 内置 imagegen、Agnes、火山方舟 Seedream 和破局问问 GPT Image）、风格训练及移动端质检。内置多种预设风格（如暖白手绘、蓝栏柔彩、小林系列等），通过确定性排版将分镜组…",
    "author": "小王AI 智能体",
    "folder": "微信公众号漫画长图",
    "zip": "resources/skill-kit/packs/171-微信公众号漫画长图.zip",
    "page": "resources/skill-kit/index.html#poju-171"
  },
  {
    "n": 172,
    "id": "poju-172",
    "name": "标书撰写助手",
    "cat": "写作",
    "brief": "通用标书（技术方案）制作技能。适用于政府和企业任意行业的招投标技术标书编写，覆盖招标文件解析、MECE框架生成、逐章编写、合稿质检、专家评审、修改迭代全流程。当用户需要写标书、做投标方案、编写技术标、制作投标文件、响应招标文件时触发此技能。关键词：标书、投标、招标、技术方案、投标文件、tender、bid、propos…",
    "author": "喜乐",
    "folder": "标书撰写助手",
    "zip": "resources/skill-kit/packs/172-标书撰写助手.zip",
    "page": "resources/skill-kit/index.html#poju-172"
  },
  {
    "n": 173,
    "id": "poju-173",
    "name": "微信公众号文章采集",
    "cat": "自动化",
    "brief": "一个用于采集微信公众号历史文章的自动化脚本。支持提取文章标题、正文文本、Markdown 格式及静态图片，并收集阅读、点赞、在看、转发、收藏等互动指标。可选采集公开一级评论（需用户显式确认）。数据以 CSV 和 Markdown 文件形式本地存储，自动处理图片去重与下载失败重试，并提供友好的配置引导流程。",
    "author": "小王AI 智能体",
    "folder": "微信公众号文章采集",
    "zip": "resources/skill-kit/packs/173-微信公众号文章采集.zip",
    "page": "resources/skill-kit/index.html#poju-173"
  },
  {
    "n": 174,
    "id": "poju-174",
    "name": "FastAPI 网站开发助手",
    "cat": "开发运维",
    "brief": "Python FastAPI 全栈管理系统开发向导，用于从零构建完整的 FastAPI + SQLAlchemy + MySQL + Vue 3 前后端分离管理系统。该技能自动执行信息收集、需求分析、功能设计、代码生成、依赖安装、数据库初始化及项目启动验证。支持管理员端与用户端的差异化布局设计，内置 JWT 认证、文件…",
    "author": "予贝",
    "folder": "FastAPI 网站开发助手",
    "zip": "resources/skill-kit/packs/174-FastAPI-网站开发助手.zip",
    "page": "resources/skill-kit/index.html#poju-174"
  },
  {
    "n": 175,
    "id": "poju-175",
    "name": "招聘邮箱监控",
    "cat": "自动化",
    "brief": "在 Windows 本地配置并定时监控网易、QQ、新浪和 Outlook 招聘邮箱。支持通过 IMAP 或 Microsoft Graph 增量收信，自动解析正文及 PDF/DOCX/DOC/TXT 附件，利用规则引擎识别简历投递并提取候选人关键字段。使用 SQLite 进行数据去重与存储，最终导出 Excel 或 J…",
    "author": "太阳鸟",
    "folder": "招聘邮箱监控",
    "zip": "resources/skill-kit/packs/175-招聘邮箱监控.zip",
    "page": "resources/skill-kit/index.html#poju-175"
  },
  {
    "n": 176,
    "id": "poju-176",
    "name": "微信公众号草稿发布",
    "cat": "自动化",
    "brief": "一款用于微信公众号草稿发布的自动化工具。支持跨平台运行，可将 Markdown 格式的文章安全排版并上传至公众号草稿箱。具备代码高亮、多主题切换、本地及网络图片处理功能，并支持多账号凭据管理。仅创建草稿，不执行群发或发表操作，确保发布过程的安全与可控。",
    "author": "gumasakiya",
    "folder": "微信公众号草稿发布",
    "zip": "resources/skill-kit/packs/176-微信公众号草稿发布.zip",
    "page": "resources/skill-kit/index.html#poju-176"
  },
  {
    "n": 177,
    "id": "poju-177",
    "name": "周报与进展汇报",
    "cat": "办公文档",
    "brief": "将零散的工作记录整理为结构化的个人、团队、管理层或客户版周报。提供多种报告模板（如个人状态、团队汇总、高管摘要、客户进度），并包含具体的写作指南，帮助用户清晰展示成果、阻塞项及下周计划。支持自定义受众、长度和语气，适用于日常汇报与项目进度同步。",
    "author": "Claude Office Skills Contributors",
    "folder": "周报与进展汇报",
    "zip": "resources/skill-kit/packs/177-周报与进展汇报.zip",
    "page": "resources/skill-kit/index.html#poju-177"
  },
  {
    "n": 178,
    "id": "poju-178",
    "name": "通俗表达改写",
    "cat": "写作",
    "brief": "通俗表达改写：将专业、技术或密集文本改写成普通读者真正能理解且不失真的表达。该工具专注于解释术语、拆解复杂句式，并在不降低信息密度的前提下提升可读性。适用于向非技术人员、高管解释概念，或简化过于晦涩的草稿。它强调保留关键数字、不确定性和限制条件，避免过度简化导致的误导，确保读者在获得易懂内容的同时，仍能准确理解原意及其…",
    "author": "Arjun Prabhulal",
    "folder": "通俗表达改写",
    "zip": "resources/skill-kit/packs/178-通俗表达改写.zip",
    "page": "resources/skill-kit/index.html#poju-178"
  },
  {
    "n": 179,
    "id": "poju-179",
    "name": "Slack 动图制作",
    "cat": "音视频",
    "brief": "Slack 动图制作工具包。提供创建优化为 Slack 使用的动画 GIF 的知识、约束条件和实用程序。支持生成符合 Slack Emoji (128x128) 或消息配图 (480x480) 标准的 GIF，包含帧构建、颜色优化、去重、缓动函数及验证功能。适用于需要快速生成合规动态图像的场景。",
    "author": "Anthropic",
    "folder": "Slack 动图制作",
    "zip": "resources/skill-kit/packs/179-Slack-动图制作.zip",
    "page": "resources/skill-kit/index.html#poju-179"
  },
  {
    "n": 180,
    "id": "poju-180",
    "name": "Markdown 转电子书",
    "cat": "办公文档",
    "brief": "将 Markdown 文档、笔记或聊天总结转换为带有目录和排版的 EPUB 电子书。支持自动识别章节结构（H1/H2）、生成导航目录、保留代码高亮与表格样式，兼容主流阅读器及 Kindle。",
    "author": "Scott Smerchek",
    "folder": "Markdown 转电子书",
    "zip": "resources/skill-kit/packs/180-Markdown-转电子书.zip",
    "page": "resources/skill-kit/index.html#poju-180"
  },
  {
    "n": 181,
    "id": "poju-181",
    "name": "商务提案写作",
    "cat": "办公文档",
    "brief": "商务提案写作助手，帮助用户从客户需求、解决方案、报价到时间表，快速生成结构完整、具有说服力的商务提案草稿。支持销售提案、项目提案、合作伙伴协议及 RFP 响应等多种场景，提供标准模板和最佳实践指导，提升提案专业度与成交率。",
    "author": "Claude Office Skills Contributors",
    "folder": "商务提案写作",
    "zip": "resources/skill-kit/packs/181-商务提案写作.zip",
    "page": "resources/skill-kit/index.html#poju-181"
  },
  {
    "n": 182,
    "id": "poju-182",
    "name": "产品发布帖写作",
    "cat": "写作",
    "brief": "专为独立开发者设计的 X (Twitter) 产品发布帖写作助手。它能根据用户提供的产品信息，生成简洁有力的单条推文或 2-4 条的短线程文案。遵循“展示而非承诺”、“前80字符决定一切”等最佳实践，强调真实价值与具体证据，避免营销噱头。支持中英双语输出，适用于新产品上线、功能更新或 Side Project 推广场景…",
    "author": "Maxiom-Rock",
    "folder": "产品发布帖写作",
    "zip": "resources/skill-kit/packs/182-产品发布帖写作.zip",
    "page": "resources/skill-kit/index.html#poju-182"
  },
  {
    "n": 183,
    "id": "poju-183",
    "name": "内容发布前质检",
    "cat": "写作",
    "brief": "内容发布前质检框架：提供从事实准确性、结构清晰度、语气一致性到品牌契合度的全方位稿件审查指南。涵盖简报遵循度检查、AI生成内容审计（识别幻觉与AI痕迹）、SEO/AEO合规性验证以及大规模程序化内容的抽样策略。旨在帮助编辑和内容团队建立高效的质量控制流程，避免形式主义审查，确保发布内容的高质量与安全性。",
    "author": "RampStack",
    "folder": "内容发布前质检",
    "zip": "resources/skill-kit/packs/183-内容发布前质检.zip",
    "page": "resources/skill-kit/index.html#poju-183"
  },
  {
    "n": 184,
    "id": "poju-184",
    "name": "简历岗位定制",
    "cat": "办公文档",
    "brief": "这是一个简历岗位定制助手 Skill。它能分析目标职位的描述，提取关键技能和要求，并据此优化您的简历内容。主要功能包括：识别 ATS（申请人跟踪系统）关键词、重构工作经历以突出相关技能、量化成就描述以及调整行业特定术语。该工具严格遵循真实性原则，不虚构任何经历，旨在帮助求职者提高简历与职位的匹配度，从而增加获得面试的机…",
    "author": "Claude Office Skills Contributors",
    "folder": "简历岗位定制",
    "zip": "resources/skill-kit/packs/184-简历岗位定制.zip",
    "page": "resources/skill-kit/index.html#poju-184"
  },
  {
    "n": 185,
    "id": "poju-185",
    "name": "卡点行动拆解",
    "cat": "工具",
    "brief": "卡点行动拆解：通过简短的引导式提问，帮助用户澄清模糊任务的预期产出，将其范围缩小到当天可完成的粒度，并识别出具体、可执行的第一步行动。适用于用户感到停滞、任务不明确或难以启动时，快速生成清晰的行动卡片，促进高效执行。",
    "author": "Michał Parkoła",
    "folder": "卡点行动拆解",
    "zip": "resources/skill-kit/packs/185-卡点行动拆解.zip",
    "page": "resources/skill-kit/index.html#poju-185"
  },
  {
    "n": 186,
    "id": "poju-186",
    "name": "长内容跨平台拆解",
    "cat": "写作",
    "brief": "一份资深内容主编的跨格式内容改编指南。帮助团队将一篇核心长内容（如白皮书、深度文章）高效转化为博客系列、邮件序列、社交媒体帖子、网络研讨会、播客和视频短片等多种衍生形式。本 Skill 强调按媒介特性进行适配，避免简单的复制粘贴（Mass-blast），确保品牌语气一致并提升各平台的互动效果。涵盖选题筛选、格式适配模式…",
    "author": "RampStack",
    "folder": "长内容跨平台拆解",
    "zip": "resources/skill-kit/packs/186-长内容跨平台拆解.zip",
    "page": "resources/skill-kit/index.html#poju-186"
  },
  {
    "n": 187,
    "id": "poju-187",
    "name": "学习成果行动转化",
    "cat": "学习教育",
    "brief": "将 YouTube 转录稿、文章和教程等被动学习内容转化为可执行的 Ship-Learn-Next 行动计划。该 Skill 帮助用户提取核心教训，定义具体目标，并设计分阶段的迭代步骤（Reps），强调“做中学”而非单纯的知识积累。适用于希望将理论知识转化为实际成果、制定短期可交付练习或构建学习挑战的用户。通过结构化的…",
    "author": "Michał Parkoła",
    "folder": "学习成果行动转化",
    "zip": "resources/skill-kit/packs/187-学习成果行动转化.zip",
    "page": "resources/skill-kit/index.html#poju-187"
  },
  {
    "n": 188,
    "id": "poju-188",
    "name": "内容选题矩阵",
    "cat": "写作",
    "brief": "基于 Justin Welsh 内容矩阵模型，帮助用户系统化生成月度社交媒体选题库。该技能将用户的内容支柱与8种经过验证的表达形式（如行动指南、激励故事、分析对比等）进行组合，一次性生成32+个具体的帖子创意。支持自动读取用户的个人简介和语气文件以定制内容，并根据运行环境（Claude.ai、Claude Code或普…",
    "author": "Charlie Hills",
    "folder": "内容选题矩阵",
    "zip": "resources/skill-kit/packs/188-内容选题矩阵.zip",
    "page": "resources/skill-kit/index.html#poju-188"
  },
  {
    "n": 189,
    "id": "poju-189",
    "name": "社交媒体帖子写作",
    "cat": "写作",
    "brief": "结合个人定位与表达风格，分步完成可发布的社交媒体帖子草稿。该技能通过读取项目中的 about-me.md 和 voice.md 文件来理解用户的个人品牌声音，支持从主题构思、角度选择到框架匹配的全流程辅助。它能根据用户提供的笔记、转录文本或具体想法，生成符合特定语气、节奏和禁用词规则的 LinkedIn 帖子草稿，并输…",
    "author": "Charlie Hills",
    "folder": "社交媒体帖子写作",
    "zip": "resources/skill-kit/packs/189-社交媒体帖子写作.zip",
    "page": "resources/skill-kit/index.html#poju-189"
  },
  {
    "n": 190,
    "id": "poju-190",
    "name": "社媒钩子开头生成",
    "cat": "写作",
    "brief": "专为 LinkedIn 等社交媒体平台设计的开头生成器。它能根据用户提供的主题，快速生成 6 种具有吸引力的“钩子”（Hook）变体。每个钩子遵循特定的公式：第一行不超过 40 字符的引人入胜的开场白，第二行不超过 40 字符的强烈对比或反转。生成的内容包含数字指标、“How I”或“I”陈述，并涵盖数字引导、反直觉、…",
    "author": "Charlie Hills",
    "folder": "社媒钩子开头生成",
    "zip": "resources/skill-kit/packs/190-社媒钩子开头生成.zip",
    "page": "resources/skill-kit/index.html#poju-190"
  },
  {
    "n": 191,
    "id": "poju-191",
    "name": "知识闪卡制作",
    "cat": "学习教育",
    "brief": "知识闪卡制作：将课程、文章或笔记拆分为清晰的问答闪卡，优化间隔重复与记忆效果。支持生成 Anki (TSV/CSV)、Quizlet 兼容格式或纯文本。遵循原子性原则，确保每张卡片只测试一个知识点，并提供助记符、上下文备注及标签建议。适用于语言学习、医学/法律术语、编程语法等场景的快速复习准备。",
    "author": "Adam Parszewski",
    "folder": "知识闪卡制作",
    "zip": "resources/skill-kit/packs/191-知识闪卡制作.zip",
    "page": "resources/skill-kit/index.html#poju-191"
  },
  {
    "n": 192,
    "id": "poju-192",
    "name": "会议纪要整理",
    "cat": "办公文档",
    "brief": "将杂乱的会议记录、转录文本或音频摘要整理为结构清晰的会议纪要。支持提取关键讨论点、已做出的决策以及具体的行动项（含负责人和截止日期）。提供多种模板，包括标准会议总结、每日站会记录、客户会议笔记和项目评审报告。适用于团队协作、项目管理和日常办公场景，帮助快速生成专业规范的会议文档。",
    "author": "Claude Office Skills Contributors",
    "folder": "会议纪要整理",
    "zip": "resources/skill-kit/packs/192-会议纪要整理.zip",
    "page": "resources/skill-kit/index.html#poju-192"
  },
  {
    "n": 193,
    "id": "poju-193",
    "name": "全链路内容生产",
    "cat": "写作",
    "brief": "全链路内容生产工作流，将主题从零转化为发布就绪的文章。提供研究简报、草稿撰写及优化润色三种模式。内置四个离线 Python 工具：品牌语气分析器、内容质量门禁检查器、综合评分器（涵盖可读性、SEO、结构和参与度）以及 SEO 优化器。无需网络连接，专注于提升内容的搜索排名、阅读体验和转化效果。",
    "author": "Alireza Rezvani",
    "folder": "全链路内容生产",
    "zip": "resources/skill-kit/packs/193-全链路内容生产.zip",
    "page": "resources/skill-kit/index.html#poju-193"
  },
  {
    "n": 194,
    "id": "poju-194",
    "name": "SaaS 产品上市规划",
    "cat": "工具",
    "brief": "一款专注于 SaaS 产品发布与功能公告的策略规划助手。它提供从内部测试到全面上市的五阶段发布框架，涵盖邮件列表、社交媒体等自有、租赁及借用渠道的运营策略。内置 Product Hunt 专项指南及发布后持续营销建议。附带一个纯 Python 标准库实现的上线准备度评分器，可量化评估产品、营销和技术维度的就绪状态，生成…",
    "author": "Alireza Rezvani",
    "folder": "SaaS 产品上市规划",
    "zip": "resources/skill-kit/packs/194-SaaS-产品上市规划.zip",
    "page": "resources/skill-kit/index.html#poju-194"
  },
  {
    "n": 195,
    "id": "poju-195",
    "name": "营销心理学",
    "cat": "工具",
    "brief": "这是一个专注于营销心理学的专业助手 Skill。它整合了 70 多种经过整理的心智模型和行为科学原理，专门用于解决市场营销中的实际问题。通过该 Skill，用户可以诊断转化率低的原因、利用心理学原则优化落地页和定价策略，并获取具体的文案改进建议。内容涵盖基础思维、买家心理、说服影响力、定价心理学、设计交付以及增长扩展等…",
    "author": "Alireza Rezvani",
    "folder": "营销心理学",
    "zip": "resources/skill-kit/packs/195-营销心理学.zip",
    "page": "resources/skill-kit/index.html#poju-195"
  },
  {
    "n": 196,
    "id": "poju-196",
    "name": "团队沟通写作",
    "cat": "办公文档",
    "brief": "一款专注于企业内部沟通的写作辅助技能。支持生成 3P 更新（进度/计划/问题）、全员新闻通讯、常见问题解答汇总、事故报告及一般性内部通告。通过匹配关键词自动路由至相应的参考模板，遵循严格的结构和语气规范，帮助用户高效撰写专业、简洁的内部文档。",
    "author": "Alireza Rezvani",
    "folder": "团队沟通写作",
    "zip": "resources/skill-kit/packs/196-团队沟通写作.zip",
    "page": "resources/skill-kit/index.html#poju-196"
  },
  {
    "n": 197,
    "id": "poju-197",
    "name": "产品经理工具箱",
    "cat": "工具",
    "brief": "产品经理工具箱，提供 RICE 优先级排序、客户访谈分析、PRD 模板及多种产品管理框架参考。支持通过命令行运行 Python 脚本进行特征优先级计算、投资组合分析及用户访谈文本的情感与主题提取，帮助产品经理高效完成需求评估、用户研究和路线图规划。",
    "author": "Alireza Rezvani",
    "folder": "产品经理工具箱",
    "zip": "resources/skill-kit/packs/197-产品经理工具箱.zip",
    "page": "resources/skill-kit/index.html#poju-197"
  },
  {
    "n": 198,
    "id": "poju-198",
    "name": "决策记录与追踪",
    "cat": "工具",
    "brief": "这是一个专为董事会会议设计的决策记录与追踪工具。采用双层记忆架构：Layer 1 存储原始会议转录，Layer 2 仅存储创始人批准的决策。提供 CLI 命令用于查看决策历史、检查逾期行动项、按负责人筛选及搜索关键词。内置冲突检测机制，防止已否决提案被重新提出。支持生成摘要报告，帮助管理层快速掌握项目进度和风险。",
    "author": "Alireza Rezvani",
    "folder": "决策记录与追踪",
    "zip": "resources/skill-kit/packs/198-决策记录与追踪.zip",
    "page": "resources/skill-kit/index.html#poju-198"
  },
  {
    "n": 199,
    "id": "poju-199",
    "name": "市场调研",
    "cat": "研究检索",
    "brief": "提供严谨的市场调研方法论工具：同时采用自上而下和自下而上方法计算 TAM/SAM/SOM 并交叉验证；根据置信度、误差范围和有限总体校正规划调查样本量及分群最小值；基于 Kotler 标准对候选市场细分进行评分和筛选。所有输出均附带方法和假设说明，确保数据可追溯。适用于市场分析人员和产品经理在制定策略前的证据构建阶段。",
    "author": "Alireza Rezvani",
    "folder": "市场调研",
    "zip": "resources/skill-kit/packs/199-市场调研.zip",
    "page": "resources/skill-kit/index.html#poju-199"
  },
  {
    "n": 200,
    "id": "poju-200",
    "name": "产品机会树与假设验证",
    "cat": "研究检索",
    "brief": "这是一个专注于产品发现阶段的结构化工作流助手。它提供了基于 Opportunity Solution Tree (OST) 的方法论指导，涵盖从定义目标、构建机会树、映射假设到验证问题和解决方案的完整流程。内置 Python 脚本 &#x27;assumption_mapper.py&#x27; 可读取 CSV 文件或命令行参数，根据风险…",
    "author": "Alireza Rezvani",
    "folder": "产品机会树与假设验证",
    "zip": "resources/skill-kit/packs/200-产品机会树与假设验证.zip",
    "page": "resources/skill-kit/index.html#poju-200"
  },
  {
    "n": 201,
    "id": "poju-201",
    "name": "竞品深度拆解",
    "cat": "研究检索",
    "brief": "一款强大的竞品拆解与分析工具，专为产品团队设计。它通过整合定价页面、应用商店评论、招聘启事、SEO 信号和社交媒体等多源数据，生成结构化的竞争情报。核心功能包括：基于 12 个维度的特征对比矩阵打分、SWOT 分析、定位地图绘制、UX 审计、定价模型拆解以及行动路线图制定。内置 Python 脚本可自动计算加权得分并生…",
    "author": "Alireza Rezvani",
    "folder": "竞品深度拆解",
    "zip": "resources/skill-kit/packs/201-竞品深度拆解.zip",
    "page": "resources/skill-kit/index.html#poju-201"
  },
  {
    "n": 202,
    "id": "poju-202",
    "name": "品牌一致性检查",
    "cat": "设计",
    "brief": "一个专业的品牌指南管理助手，帮助用户应用、文档化或强制执行任何产品或公司的品牌规范。涵盖色彩系统、字体排印、Logo 使用规则、图像指南以及语气矩阵。内置 Anthropic 官方身份识别作为示例，并提供通用的品牌构建框架，支持快速审计品牌一致性、生成品牌审计报告及定义视觉与语调标准。适用于市场营销、产品设计和品牌管理…",
    "author": "Alireza Rezvani",
    "folder": "品牌一致性检查",
    "zip": "resources/skill-kit/packs/202-品牌一致性检查.zip",
    "page": "resources/skill-kit/index.html#poju-202"
  },
  {
    "n": 203,
    "id": "poju-203",
    "name": "SaaS 营销策略库",
    "cat": "工具",
    "brief": "一个专为 SaaS 和软件产品设计的营销灵感库，提供 139 种经过验证的营销策略。涵盖内容 SEO、付费广告、社交媒体、电子邮件营销、合作伙伴关系、活动策划等多个类别。用户可根据产品阶段、预算和时间线获取定制化的营销建议和实施步骤。",
    "author": "Alireza Rezvani",
    "folder": "SaaS 营销策略库",
    "zip": "resources/skill-kit/packs/203-SaaS-营销策略库.zip",
    "page": "resources/skill-kit/index.html#poju-203"
  },
  {
    "n": 204,
    "id": "poju-204",
    "name": "内容策略规划",
    "cat": "写作",
    "brief": "这是一个内容策略规划助手，帮助用户制定内容计划、确定创作方向及挖掘选题。它通过引导式提问收集业务背景、客户研究和竞争情报，输出包含内容支柱、优先级主题和主题聚类地图的策略方案。内置 Python 脚本可基于关键词列表自动生成主题聚类分析，辅助识别核心话题组。适用于需要系统化内容规划、SEO 基础建设及提升内容营销效率的…",
    "author": "Alireza Rezvani",
    "folder": "内容策略规划",
    "zip": "resources/skill-kit/packs/204-内容策略规划.zip",
    "page": "resources/skill-kit/index.html#poju-204"
  },
  {
    "n": 205,
    "id": "poju-205",
    "name": "营销文案写作",
    "cat": "写作",
    "brief": "专业营销文案写作助手。提供撰写、重写和优化各类营销页面（如首页、落地页、定价页、功能页等）的文案指导。内置转化文案核心原则（如清晰度优于创意、利益点优于特性）、不同页面的结构框架（Hero区、社会证明、痛点解决等）、CTA 文案公式以及语气风格指南。附带一个纯 Python 编写的标题评分脚本，可离线对标题进行多维度打…",
    "author": "Alireza Rezvani",
    "folder": "营销文案写作",
    "zip": "resources/skill-kit/packs/205-营销文案写作.zip",
    "page": "resources/skill-kit/index.html#poju-205"
  },
  {
    "n": 206,
    "id": "poju-206",
    "name": "营销文案编辑",
    "cat": "写作",
    "brief": "这是一个专业的营销文案编辑助手。它提供了一套系统的“七步扫描”编辑法，从清晰度、语气、价值主张、证据支持、具体性、情感共鸣到消除风险障碍，逐层优化现有文案。此外，它还包含两个离线 Python 工具：一个用于评估文案的可读性（基于 Flesch 评分、被动语态比例等指标），另一个用于检测文案中可能由 AI 生成的模式（…",
    "author": "Alireza Rezvani",
    "folder": "营销文案编辑",
    "zip": "resources/skill-kit/packs/206-营销文案编辑.zip",
    "page": "resources/skill-kit/index.html#poju-206"
  },
  {
    "n": 207,
    "id": "poju-207",
    "name": "创意方案打磨",
    "cat": "工具",
    "brief": "这是一个结构化的创意精炼助手，通过引导式的发散思维和收敛思考，帮助用户将模糊的原始想法转化为清晰、可执行的概念。它适用于需要压力测试假设、拓展选项或最终确定方向的各种场景。Skill 内置了三个核心阶段：首先通过提问和多种思维透镜（如逆向思维、约束移除等）扩展思路；其次对生成的方向进行价值、可行性和差异化评估，并揭示隐…",
    "author": "Addy Osmani",
    "folder": "创意方案打磨",
    "zip": "resources/skill-kit/packs/207-创意方案打磨.zip",
    "page": "resources/skill-kit/index.html#poju-207"
  },
  {
    "n": 208,
    "id": "poju-208",
    "name": "海报与静态视觉设计",
    "cat": "设计",
    "brief": "这是一个用于创建高质量视觉艺术作品的技能包。它通过引导 AI 遵循特定的设计哲学（如极简主义、构成主义等），生成 .png 和 .pdf 格式的海报、艺术品或静态设计稿。该 Skill 内置了多种经过 OFL 许可的开源字体（如 ArsenalSC, BigShoulders, CrimsonPro 等），确保在生成包…",
    "author": "Anthropic, PBC",
    "folder": "海报与静态视觉设计",
    "zip": "resources/skill-kit/packs/208-海报与静态视觉设计.zip",
    "page": "resources/skill-kit/index.html#poju-208"
  },
  {
    "n": 209,
    "id": "poju-209",
    "name": "文档主题美化",
    "cat": "设计",
    "brief": "Theme Factory 是一款用于为幻灯片、文档、报告及 HTML 落地页等工件添加专业主题样式的工具包。内置 10 种精心设计的预设主题（如 Ocean Depths, Modern Minimalist 等），涵盖配色方案与字体搭配。用户可预览主题展示文件并选择适用风格，系统将指导如何应用选定的颜色和字体以保持…",
    "author": "Anthropic, PBC",
    "folder": "文档主题美化",
    "zip": "resources/skill-kit/packs/209-文档主题美化.zip",
    "page": "resources/skill-kit/index.html#poju-209"
  },
  {
    "n": 210,
    "id": "poju-210",
    "name": "内部沟通文档写作",
    "cat": "办公文档",
    "brief": "一套帮助撰写各类内部沟通文档的资源库，包含进度更新(3P)、公司新闻通讯、常见问题解答(FAQ)及通用沟通的格式规范和写作指南。适用于状态报告、领导层汇报、项目更新等场景。",
    "author": "Anthropic, PBC",
    "folder": "内部沟通文档写作",
    "zip": "resources/skill-kit/packs/210-内部沟通文档写作.zip",
    "page": "resources/skill-kit/index.html#poju-210"
  },
  {
    "n": 211,
    "id": "poju-211",
    "name": "思绪捕捉与整理",
    "cat": "工具",
    "brief": "将混乱的头脑风暴转化为结构化、可执行的系统，确保信息零丢失。当用户表达需要整理思绪、倾倒想法或粘贴大量无序内容时触发。输出包含项目/想法、任务、关联和建议四个部分，并在必要时提出澄清问题，帮助用户理清思路并制定行动计划。",
    "author": "Alireza Rezvani",
    "folder": "思绪捕捉与整理",
    "zip": "resources/skill-kit/packs/211-思绪捕捉与整理.zip",
    "page": "resources/skill-kit/index.html#poju-211"
  },
  {
    "n": 212,
    "id": "poju-212",
    "name": "深度需求访谈",
    "cat": "研究检索",
    "brief": "通过一次一问的访谈方式，挖掘用户真正的需求而非表面想法，直至对底层意图达到约95%的置信度。适用于需求描述模糊（如仅说“构建X”但未说明目标受众或紧迫性）、用户明确请求（如“采访我”、“拷问我”、“确认一下？”、“压力测试我的思路”），或在制定计划、规范或编写代码前察觉自身正在填补模糊需求的情况。",
    "author": "Addy Osmani",
    "folder": "深度需求访谈",
    "zip": "resources/skill-kit/packs/212-深度需求访谈.zip",
    "page": "resources/skill-kit/index.html#poju-212"
  },
  {
    "n": 213,
    "id": "poju-213",
    "name": "去AI味",
    "cat": "写作",
    "brief": "从文本中去除人工智能生成内容的痕迹。在编辑或审阅文本时使用，使内容听起来更自然、更像人工撰写。基于维基百科全面的“AI写作特征”指南，检测和修复以下模式：过度象征化、宣传性语言、浅层的-ing分析、模糊的归因、破折号滥用、三段式结构、AI常用词汇、被动语态、负面平行结构以及填充短语。",
    "author": "Siqi Chen",
    "folder": "去AI味",
    "zip": "resources/skill-kit/packs/213-去AI味.zip",
    "page": "resources/skill-kit/index.html#poju-213"
  }
];
