const fs=require('fs');const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const report=[];fs.mkdirSync('.qa/display',{recursive:true});
for(const width of [320,390,768,1024,1440,1920]){const page=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765');
 for(const view of ['guide','chapters','skills','videos','templates','faq','concepts','appendix','materials']){await page.locator('.view-nav [data-view="'+view+'"]').click();await page.waitForTimeout(250);const metrics=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));if(metrics.scroll>width+1)errors.push(view+' overflow '+metrics.scroll);}
 await page.locator('.view-nav [data-view="guide"]').click();await page.locator('[data-guide="layout"]').click();if(!await page.locator('#guide-body h2').textContent().then(t=>t==='你要做什么，就读对应的章节'))errors.push('guide label');
 if([390,768,1440].includes(width)){await page.screenshot({animations:"disabled",path:'.qa/display/guide-'+width+'.png',fullPage:false});await page.locator('.view-nav [data-view="videos"]').click();await page.screenshot({animations:"disabled",path:'.qa/display/videos-'+width+'.png',fullPage:false});await page.locator('.view-nav [data-view="chapters"]').click();await page.locator('#ch-detail').scrollIntoViewIfNeeded();await page.screenshot({animations:"disabled",path:'.qa/display/chapter-'+width+'.png',fullPage:false});}
 report.push({width,errors});await page.close();}
 const p=await browser.newPage({viewport:{width:1400,height:1000}});await p.goto('http://127.0.0.1:8765/#chapters-1');await p.locator('.chapter-map img').screenshot({path:'.qa/display/map-01.png'});await browser.close();fs.writeFileSync('.qa/display/report.json',JSON.stringify(report,null,2));console.log(report);if(report.some(r=>r.errors.length))process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
